// SPDX-License-Identifier: GPL-3.0-or-later
//
// Knomosis — proof-carrying state transition system.
// Cross-stack consumer for the GP.11.3 embedded-AMM swap-math corpus.
//
pragma solidity ^0.8.20;

import {CrossCheckFramework} from "./Framework.t.sol";
import {AmmMath} from "src/lib/AmmMath.sol";

/// @title AmmMathCrossCheck (GP.11.3)
/// @notice Solidity-side consumer of the Lean-authored `amm_getamountout.json`
///         corpus.  Proves `Lean-spec == Solidity-formula` for the
///         constant-product pricing function `getAmountOut` over the WHOLE
///         corpus (204 entries: a 192-entry amount×reserve×reserve×fee grid
///         plus 12 boundary corners), not just the few hand-vectors the unit
///         tests pin.
///
/// @dev    Each entry carries the four `getAmountOut` inputs and the Lean
///         `LegalKernel.Bridge.AmmMath.getAmountOut`'s output (`expectedOut`).
///         This suite recomputes `src/lib/AmmMath.sol::getAmountOut` over the
///         SAME inputs and byte-matches the result.  The pricing formula is
///         pure integer arithmetic (no keccak), so the cross-check runs
///         UNCONDITIONALLY in every hash-binding mode.  Both stacks were
///         independently proven (Lean: `getAmountOut_lt_reserveOut` +
///         `k_nondecreasing`; Solidity: `AmmMath.t.sol` + `AmmInvariants.t.sol`),
///         so byte-equality of their outputs over this corpus closes the
///         "the two implementations of the same formula agree" gap.
///
///         Every check guards on `fixtureExists` so the suite skips
///         gracefully when the fixture has not yet been generated by
///         `lake test`.  The Lean generator wraps corpus metadata under a
///         top-level `header` object.
contract AmmMathCrossCheck is CrossCheckFramework {
    /// @dev Fixture file name under `test/CrossCheck/fixtures/`.
    string internal constant FIXTURE_NAME = "amm_getamountout.json";

    /// @dev Mirror of `KnomosisBridge.AMM_SWAP_FEE_BPS` (the production fee).
    uint256 internal constant AMM_SWAP_FEE_BPS = 30;

    /// @dev Decoded fixture entry.  `amountIn` / `reserveIn` / `reserveOut` /
    ///      `expectedOut` are 32-byte BE hex (parsed as `uint256`); `feeBps`
    ///      is a small JSON number.
    struct Entry {
        uint256 amountIn;
        uint256 reserveIn;
        uint256 reserveOut;
        uint256 feeBps;
        uint256 expectedOut;
    }

    // ------------------------------------------------------------------
    // Fixture decoding
    // ------------------------------------------------------------------

    /// @dev The corpus entry count, read from the nested `.header.count`.
    function _count(string memory raw) internal pure returns (uint256) {
        return vm.parseJsonUint(raw, ".header.count");
    }

    /// @dev Load entry `i` from the raw JSON.
    function _loadEntry(string memory raw, uint256 i) internal pure returns (Entry memory e) {
        string memory base = string.concat(".entries[", vm.toString(i), "]");
        e.amountIn = uint256(vm.parseJsonBytes32(raw, string.concat(base, ".amountIn")));
        e.reserveIn = uint256(vm.parseJsonBytes32(raw, string.concat(base, ".reserveIn")));
        e.reserveOut = uint256(vm.parseJsonBytes32(raw, string.concat(base, ".reserveOut")));
        e.feeBps = vm.parseJsonUint(raw, string.concat(base, ".feeBps"));
        e.expectedOut = uint256(vm.parseJsonBytes32(raw, string.concat(base, ".expectedOut")));
    }

    // ------------------------------------------------------------------
    // Header
    // ------------------------------------------------------------------

    /// @notice The header pins the corpus shape: a non-empty entry count, the
    ///         shared `bpsDenominator == AmmMath.BPS_DENOMINATOR`, and the
    ///         production `ammSwapFeeBps == AMM_SWAP_FEE_BPS`.
    function test_header_shape() public {
        if (!fixtureExists(FIXTURE_NAME)) {
            _skipWithReason("amm_getamountout.json not generated (run `lake test`)");
            return;
        }
        string memory raw = readFixture(FIXTURE_NAME);

        assertGt(_count(raw), 0, "corpus is non-empty");
        assertEq(
            vm.parseJsonUint(raw, ".header.bpsDenominator"),
            AmmMath.BPS_DENOMINATOR,
            "bpsDenominator matches the Solidity library"
        );
        assertEq(
            vm.parseJsonUint(raw, ".header.ammSwapFeeBps"), AMM_SWAP_FEE_BPS, "production fee pinned"
        );
        assertEq(vm.parseJsonString(raw, ".header.workstream"), "GP.11.3", "workstream tag");
    }

    // ------------------------------------------------------------------
    // Per-entry byte equivalence (the headline check)
    // ------------------------------------------------------------------

    /// @notice For EVERY corpus entry, the Solidity `AmmMath.getAmountOut`
    ///         reproduces the Lean `expectedOut` byte-for-byte.  This is the
    ///         headline `Lean-spec == Solidity-formula` equivalence.
    function test_perEntry_getAmountOut_matchesLean() public {
        if (!fixtureExists(FIXTURE_NAME)) {
            _skipWithReason("amm_getamountout.json not generated (run `lake test`)");
            return;
        }
        string memory raw = readFixture(FIXTURE_NAME);
        uint256 n = _count(raw);

        for (uint256 i = 0; i < n; i++) {
            Entry memory e = _loadEntry(raw, i);
            uint256 got = AmmMath.getAmountOut(e.amountIn, e.reserveIn, e.reserveOut, e.feeBps);
            assertEq(got, e.expectedOut, "Solidity getAmountOut diverges from Lean");
        }
    }

    // ------------------------------------------------------------------
    // Proof-carrying properties, re-checked on the Solidity side
    // ------------------------------------------------------------------

    /// @notice No-drain: every entry satisfies `expectedOut < reserveOut`
    ///         (Lean's `getAmountOut_lt_reserveOut`, re-verified here).  A swap
    ///         can never empty the output reserve.
    function test_perEntry_noDrain() public {
        if (!fixtureExists(FIXTURE_NAME)) {
            _skipWithReason("amm_getamountout.json not generated (run `lake test`)");
            return;
        }
        string memory raw = readFixture(FIXTURE_NAME);
        uint256 n = _count(raw);

        for (uint256 i = 0; i < n; i++) {
            Entry memory e = _loadEntry(raw, i);
            assertLt(e.expectedOut, e.reserveOut, "no-drain violated (output >= reserveOut)");
        }
    }

    /// @notice k-monotonicity: the constant product never decreases across a
    ///         swap (Lean's `k_nondecreasing`, re-verified here).  Using the
    ///         FULL input on the input leg and `reserveOut - expectedOut` on
    ///         the output leg, `reserveIn * reserveOut <= (reserveIn +
    ///         amountIn) * (reserveOut - expectedOut)`.
    function test_perEntry_kNonDecreasing() public {
        if (!fixtureExists(FIXTURE_NAME)) {
            _skipWithReason("amm_getamountout.json not generated (run `lake test`)");
            return;
        }
        string memory raw = readFixture(FIXTURE_NAME);
        uint256 n = _count(raw);

        for (uint256 i = 0; i < n; i++) {
            Entry memory e = _loadEntry(raw, i);
            uint256 kBefore = e.reserveIn * e.reserveOut;
            uint256 kAfter = (e.reserveIn + e.amountIn) * (e.reserveOut - e.expectedOut);
            assertLe(kBefore, kAfter, "k decreased across the swap");
        }
    }

    // ------------------------------------------------------------------
    // Hand-vector anchor (non-circular ground truth)
    // ------------------------------------------------------------------

    /// @notice Anchor the corpus to hand-computed ground truth so a bug that
    ///         corrupted BOTH the Lean generator and this consumer identically
    ///         would still be caught: `getAmountOut(1000, 1000, 1000, 0) == 500`
    ///         (the no-fee half-pool case) and `... 30) == 499` (the 0.30%-fee
    ///         case).
    function test_handVectors_knownGroundTruth() public pure {
        assertEq(AmmMath.getAmountOut(1000, 1000, 1000, 0), 500, "no-fee half-pool");
        assertEq(AmmMath.getAmountOut(1000, 1000, 1000, 30), 499, "0.30%-fee half-pool");
    }
}
