// SPDX-License-Identifier: GPL-3.0-or-later
//
// Knomosis — proof-carrying state transition system.
// Cross-stack consumer for the GP.6.5 BOLD-specific deposit corpus.
//
pragma solidity ^0.8.20;

import {Vm} from "forge-std/Vm.sol";

import {CrossCheckFramework} from "./Framework.t.sol";
import {FeeSplitMath} from "test/utils/FeeSplitMath.sol";
import {KnomosisBridge} from "src/contracts/KnomosisBridge.sol";
import {MockBold} from "test/utils/MockBold.sol";

/// @title BoldDepositFixturesCrossCheck (GP.6.5)
/// @notice Solidity-side consumer of the Lean-authored `bold_deposit.json`
///         tri-stack corpus.  Re-verifies the BOLD deposit-with-fee path
///         independently of the Lean / Rust producers:
///           * an arithmetic recompute via `FeeSplitMath.split` — every
///             entry, hash-independent;
///           * the cross-stack budget-grant semantics
///             (`recipientBudgetAfter == budgetGrant`) — the NEW GP.6.5
///             dimension carried in this corpus;
///           * ETH/BOLD calibration parity (identical inputs ⇒ identical
///             split regardless of resource);
///           * the budget-clamp corners;
///           * the `actionCbe` / `recipientBudgetCbe` CBE side-channels'
///             well-formedness; and
///           * DIRECT live-contract deposits through `depositBoldWithFee`
///             and `depositETHWithFee` whose EMITTED
///             `(userAmount, poolAmount, budgetGrant)` must byte-match the
///             Lean-generated values — removing the `FeeSplitMath`
///             intermediary from the live cross-stack path.
///
/// @dev    The split + budget-grant are hash-independent, so every check
///         runs in EVERY binding mode (FNV fallback or keccak-linked).
///         All checks guard on `fixtureExists` so the suite skips
///         gracefully when the fixture has not yet been generated by
///         `lake test`.  The Lean generator wraps the corpus metadata
///         under a top-level `header` object, so all metadata reads use
///         `.header.<field>`.
contract BoldDepositFixturesCrossCheck is CrossCheckFramework {
    /// @dev Fixture file name under `test/CrossCheck/fixtures/`.
    string internal constant FIXTURE_NAME = "bold_deposit.json";

    /// @dev Local mirror of `KnomosisBridge.BOLD_TOKEN_ADDRESS`.
    address internal constant BOLD = 0x6440f144b7e50D6a8439336510312d2F54beB01D;

    /// @dev Mirror of `KnomosisBridge.RESOURCE_ID_BOLD`.
    uint64 internal constant RESOURCE_BOLD = 1;

    /// @dev Mirror of `KnomosisBridge.RESOURCE_ID_NATIVE_ETH`.
    uint64 internal constant RESOURCE_ETH = 0;

    /// @dev GP.5.5 safety-hardening roles (non-zero + distinct so a
    ///      BOLD-enabled bridge constructs; the cross-check never exercises
    ///      them).
    address internal constant BOLD_BREAKER = address(0xB12E6B6E);
    address internal constant BOLD_ADMIN = address(0xAD814);

    /// @dev Decoded fixture entry.
    struct Entry {
        uint64 resourceId;
        uint256 amount;
        uint16 chosenFeeBps;
        uint64 weiPerBudgetUnit;
        uint64 depositId;
        uint256 userAmount;
        uint256 poolAmount;
        uint64 budgetGrant;
        uint64 recipientBudgetAfter;
    }

    /// @notice Place a conformant BOLD mock at the pinned address so
    ///         BOLD-enabled bridges can be deployed in the live-contract
    ///         checks (the constructor reads `symbol()`).
    function setUp() public {
        MockBold impl = new MockBold();
        vm.etch(BOLD, address(impl).code);
    }

    // ------------------------------------------------------------------
    // Fixture decoding
    // ------------------------------------------------------------------

    /// @dev The corpus entry count, read from the nested `.header.count`.
    function _count(string memory raw) internal pure returns (uint256) {
        return vm.parseJsonUint(raw, ".header.count");
    }

    /// @dev Load entry `i` from the raw JSON.  `amount` / `userAmount` /
    ///      `poolAmount` are hex `bytes32` (parsed as `uint256`); the
    ///      remaining fields are JSON numbers.
    function _loadEntry(string memory raw, uint256 i)
        internal
        pure
        returns (Entry memory e)
    {
        string memory base = string.concat(".entries[", vm.toString(i), "]");
        e.resourceId = uint64(vm.parseJsonUint(raw, string.concat(base, ".resourceId")));
        e.amount = uint256(vm.parseJsonBytes32(raw, string.concat(base, ".amount")));
        // forge-lint: disable-next-line(unsafe-typecast)
        e.chosenFeeBps = uint16(vm.parseJsonUint(raw, string.concat(base, ".chosenFeeBps")));
        e.weiPerBudgetUnit =
            uint64(vm.parseJsonUint(raw, string.concat(base, ".weiPerBudgetUnit")));
        e.depositId = uint64(vm.parseJsonUint(raw, string.concat(base, ".depositId")));
        e.userAmount = uint256(vm.parseJsonBytes32(raw, string.concat(base, ".userAmount")));
        e.poolAmount = uint256(vm.parseJsonBytes32(raw, string.concat(base, ".poolAmount")));
        e.budgetGrant = uint64(vm.parseJsonUint(raw, string.concat(base, ".budgetGrant")));
        e.recipientBudgetAfter =
            uint64(vm.parseJsonUint(raw, string.concat(base, ".recipientBudgetAfter")));
    }

    // ------------------------------------------------------------------
    // tests
    // ------------------------------------------------------------------

    /// @notice Header shape: a non-empty corpus plus the constitutional
    ///         caps / pins.
    function test_fixture_header_shape() public view {
        if (!fixtureExists(FIXTURE_NAME)) return;
        string memory raw = readFixture(FIXTURE_NAME);
        assertGt(_count(raw), 0, "count > 0");
        assertEq(
            vm.parseJsonUint(raw, ".header.maxBudgetPerDeposit"),
            uint256(FeeSplitMath.MAX_BUDGET_PER_DEPOSIT),
            "maxBudgetPerDeposit == 1e12"
        );
        assertEq(uint256(FeeSplitMath.MAX_BUDGET_PER_DEPOSIT), 1_000_000_000_000, "1e12");
        assertEq(vm.parseJsonUint(raw, ".header.maxFeeBpsCap"), 5000, "maxFeeBpsCap");
        assertEq(
            vm.parseJsonUint(raw, ".header.minWeiPerBudgetUnit"), 1, "minWeiPerBudgetUnit"
        );
        assertEq(
            vm.parseJsonUint(raw, ".header.resourceIdBold"),
            uint256(RESOURCE_BOLD),
            "resourceIdBold"
        );
        assertEq(
            vm.parseJsonAddress(raw, ".header.boldTokenAddress"), BOLD, "boldTokenAddress"
        );
    }

    /// @notice Hash-independent arithmetic recompute: `FeeSplitMath.split`
    ///         reproduces every entry's split exactly; conservation and the
    ///         budget-cap bound hold.
    function test_perEntry_split_matches() public view {
        if (!fixtureExists(FIXTURE_NAME)) return;
        string memory raw = readFixture(FIXTURE_NAME);
        uint256 n = _count(raw);
        for (uint256 i = 0; i < n; i++) {
            Entry memory e = _loadEntry(raw, i);
            (uint256 u, uint256 p, uint64 b) =
                FeeSplitMath.split(e.amount, e.chosenFeeBps, e.weiPerBudgetUnit);
            assertEq(u, e.userAmount, "userAmount mismatch");
            assertEq(p, e.poolAmount, "poolAmount mismatch");
            assertEq(uint256(b), uint256(e.budgetGrant), "budgetGrant mismatch");
            assertEq(u + p, e.amount, "conservation user+pool==amount");
            assertLe(
                uint256(b),
                uint256(FeeSplitMath.MAX_BUDGET_PER_DEPOSIT),
                "budget within cap"
            );
        }
    }

    /// @notice Cross-stack budget-grant semantics: from a genesis-empty
    ///         budget at epoch 0 with freeTier 0, the recipient's
    ///         post-deposit `currentBudget` equals exactly the granted
    ///         `budgetGrant`.
    function test_perEntry_budgetGrant_equals_recipientBudgetAfter()
        public
        view
    {
        if (!fixtureExists(FIXTURE_NAME)) return;
        string memory raw = readFixture(FIXTURE_NAME);
        uint256 n = _count(raw);
        for (uint256 i = 0; i < n; i++) {
            Entry memory e = _loadEntry(raw, i);
            assertEq(
                e.recipientBudgetAfter,
                e.budgetGrant,
                "recipientBudgetAfter == budgetGrant"
            );
        }
    }

    /// @notice Exactly 20 entries exercise the budget clamp corner
    ///         (`budgetGrant == MAX_BUDGET_PER_DEPOSIT`): 16 rate-1 grid
    ///         entries with a pool ≥ 10^12, plus the four rate-1
    ///         boundary legs (the two `10^18 @ 50%` and the two
    ///         `u64::MAX @ 50%` whales).  Pinned EXACTLY so a corpus
    ///         regression that drops clamp coverage cannot hide behind
    ///         a loose `≥ 5` floor; the `≥ 5` spec floor is also
    ///         (re)asserted.
    function test_clamp_corners() public view {
        if (!fixtureExists(FIXTURE_NAME)) return;
        string memory raw = readFixture(FIXTURE_NAME);
        uint256 n = _count(raw);
        uint256 clamped = 0;
        for (uint256 i = 0; i < n; i++) {
            Entry memory e = _loadEntry(raw, i);
            if (e.budgetGrant == FeeSplitMath.MAX_BUDGET_PER_DEPOSIT) {
                clamped++;
            }
        }
        assertEq(clamped, 20, "expected exactly 20 clamp-corner entries");
        assertGe(clamped, 5, "at least 5 clamp-corner entries (spec floor)");
    }

    /// @notice Grid resource-agnosticism: an ETH and a BOLD entry sharing
    ///         the FULL key `(amount, chosenFeeBps, weiPerBudgetUnit,
    ///         depositId)` must produce an identical
    ///         `(userAmount, poolAmount, budgetGrant)` split.  This is
    ///         the SAME-amount property (the 80 grid twins, all on
    ///         `depositId == 42`); it is NOT the spec's calibration
    ///         parity, which uses DIFFERENT amounts — see
    ///         `test_usd_calibration_parity` below.  Including
    ///         `depositId` in the key prevents a cross-amount
    ///         calibration entry (distinct `depositId`) from being
    ///         mistaken for a grid twin.
    function test_grid_resource_agnosticism() public view {
        if (!fixtureExists(FIXTURE_NAME)) return;
        string memory raw = readFixture(FIXTURE_NAME);
        uint256 n = _count(raw);
        Entry[] memory entries = new Entry[](n);
        for (uint256 i = 0; i < n; i++) {
            entries[i] = _loadEntry(raw, i);
        }
        uint256 pairs = 0;
        for (uint256 a = 0; a < n; a++) {
            if (entries[a].resourceId != RESOURCE_BOLD) continue;
            for (uint256 b = 0; b < n; b++) {
                if (entries[b].resourceId != RESOURCE_ETH) continue;
                if (
                    entries[a].amount == entries[b].amount
                        && entries[a].chosenFeeBps == entries[b].chosenFeeBps
                        && entries[a].weiPerBudgetUnit == entries[b].weiPerBudgetUnit
                        && entries[a].depositId == entries[b].depositId
                ) {
                    assertEq(
                        entries[a].userAmount, entries[b].userAmount, "parity userAmount"
                    );
                    assertEq(
                        entries[a].poolAmount, entries[b].poolAmount, "parity poolAmount"
                    );
                    assertEq(
                        entries[a].budgetGrant, entries[b].budgetGrant, "parity budgetGrant"
                    );
                    pairs++;
                }
            }
        }
        assertEq(pairs, 80, "expected exactly 80 ETH/BOLD grid twin pairs");
    }

    /// @notice USD-calibration parity — the spec's headline calibration
    ///         deliverable.  Each calibration pair (shared unique
    ///         `depositId >= 2000`) carries DIFFERENT amounts on its two
    ///         legs (`amount_bold == 3000 * amount_eth`) at DIFFERENT
    ///         rates (`rate_bold == 3000 * rate_eth`), calibrated to the
    ///         same USD value, yet MUST yield EQUAL budget grants.  The
    ///         calibration is exact, so the grants match exactly (the
    ///         spec's floor-division-residue tolerance is a conservative
    ///         bound this corpus beats).  Distinct from the same-amount
    ///         `test_grid_resource_agnosticism`.
    function test_usd_calibration_parity() public view {
        if (!fixtureExists(FIXTURE_NAME)) return;
        string memory raw = readFixture(FIXTURE_NAME);
        uint256 n = _count(raw);
        Entry[] memory entries = new Entry[](n);
        for (uint256 i = 0; i < n; i++) {
            entries[i] = _loadEntry(raw, i);
        }
        // Mirror of the Lean generator's calibration constants.
        uint256 rateEth = 1e12;
        uint256 rateBold = 3e15;
        uint256 ratio = 3000;
        uint256 pairs = 0;
        for (uint256 a = 0; a < n; a++) {
            if (entries[a].resourceId != RESOURCE_ETH) continue;
            if (entries[a].depositId < 2000) continue; // calibration block only
            for (uint256 b = 0; b < n; b++) {
                if (entries[b].resourceId != RESOURCE_BOLD) continue;
                if (entries[b].depositId != entries[a].depositId) continue;
                // Cross-amount, calibrated rates.
                assertTrue(
                    entries[a].amount != entries[b].amount,
                    "calibration legs must carry different amounts"
                );
                assertEq(entries[a].weiPerBudgetUnit, rateEth, "ETH leg rate != 1e12");
                assertEq(entries[b].weiPerBudgetUnit, rateBold, "BOLD leg rate != 3e15");
                assertEq(
                    entries[b].amount, ratio * entries[a].amount, "amounts not in 3000:1 ratio"
                );
                assertEq(
                    entries[a].amount * rateBold,
                    entries[b].amount * rateEth,
                    "calibration pair not USD-aligned"
                );
                // Headline: equal budget grants despite different inputs.
                assertEq(
                    entries[a].budgetGrant,
                    entries[b].budgetGrant,
                    "USD-calibration parity broken: budget_eth != budget_bold"
                );
                assertGt(entries[a].budgetGrant, 0, "calibration pair has a zero budget grant");
                pairs++;
            }
        }
        assertEq(pairs, 12, "expected exactly 12 USD-calibration pairs");
    }

    /// @notice Live-contract BOLD path: deploy a BOLD-enabled bridge
    ///         calibrated to each entry's rate, deposit via
    ///         `depositBoldWithFee`, and assert the emitted split
    ///         byte-matches the fixture.
    function test_perEntry_liveContract_bold_split_matches() public {
        if (!fixtureExists(FIXTURE_NAME)) return;
        string memory raw = readFixture(FIXTURE_NAME);
        uint256 n = _count(raw);
        address depositor = address(0xA11CE);
        for (uint256 i = 0; i < n; i++) {
            Entry memory e = _loadEntry(raw, i);
            if (e.resourceId != RESOURCE_BOLD) continue;
            KnomosisBridge bridge = _deployBoldBridge(e.weiPerBudgetUnit);
            MockBold(BOLD).mint(depositor, e.amount);
            vm.prank(depositor);
            MockBold(BOLD).approve(address(bridge), e.amount);
            vm.recordLogs();
            vm.prank(depositor);
            bridge.depositBoldWithFee(e.amount, e.chosenFeeBps);
            (uint256 u, uint256 p, uint64 b) =
                _decodeDepositWithFee(vm.getRecordedLogs());
            assertEq(u, e.userAmount, "live bold userAmount != fixture");
            assertEq(p, e.poolAmount, "live bold poolAmount != fixture");
            assertEq(uint256(b), uint256(e.budgetGrant), "live bold budgetGrant != fixture");
        }
    }

    /// @notice Live-contract ETH path: deploy a bridge whose ETH leg is
    ///         calibrated to each entry's rate (a BOLD-enabled bridge also
    ///         serves the ETH path), deposit via `depositETHWithFee`, and
    ///         assert the emitted split byte-matches the fixture.
    /// @dev `depositETHWithFee(uint16)` is `external payable`; the ETH
    ///      budget grant uses the bridge's immutable `weiPerBudgetUnitEth`,
    ///      so the bridge is constructed with
    ///      `weiPerBudgetUnitEth = entry.weiPerBudgetUnit`.
    function test_perEntry_liveContract_eth_split_matches() public {
        if (!fixtureExists(FIXTURE_NAME)) return;
        string memory raw = readFixture(FIXTURE_NAME);
        uint256 n = _count(raw);
        address depositor = address(0xA11CE);
        for (uint256 i = 0; i < n; i++) {
            Entry memory e = _loadEntry(raw, i);
            if (e.resourceId != RESOURCE_ETH) continue;
            KnomosisBridge bridge = _deployBridge(e.weiPerBudgetUnit, 1);
            vm.deal(depositor, e.amount);
            vm.recordLogs();
            vm.prank(depositor);
            bridge.depositETHWithFee{value: e.amount}(e.chosenFeeBps);
            (uint256 u, uint256 p, uint64 b) =
                _decodeDepositWithFee(vm.getRecordedLogs());
            assertEq(u, e.userAmount, "live eth userAmount != fixture");
            assertEq(p, e.poolAmount, "live eth poolAmount != fixture");
            assertEq(uint256(b), uint256(e.budgetGrant), "live eth budgetGrant != fixture");
        }
    }

    /// @notice Well-formedness of the CBE side-channels: `actionCbe` is a
    ///         0x-prefixed 72-byte hex string and `recipientBudgetCbe` an
    ///         18-byte hex string for every entry.  (Length is checked on
    ///         the hex string directly, no decode needed.  The Lean
    ///         `hexFromBytes` emits `"0x"` + two hex chars per byte with no
    ///         length prefix, so 72 bytes => 146 chars, 18 bytes => 38
    ///         chars.)
    function test_actionCbe_wellformed() public view {
        if (!fixtureExists(FIXTURE_NAME)) return;
        string memory raw = readFixture(FIXTURE_NAME);
        uint256 n = _count(raw);
        for (uint256 i = 0; i < n; i++) {
            string memory base = string.concat(".entries[", vm.toString(i), "]");
            bytes memory action =
                bytes(vm.parseJsonString(raw, string.concat(base, ".actionCbe")));
            bytes memory budget = bytes(
                vm.parseJsonString(raw, string.concat(base, ".recipientBudgetCbe"))
            );
            // 0x-prefixed.  Compare the two prefix bytes as a string
            // (no `bytes1(string)` truncating cast — keeps `forge lint`
            // clean while pinning the exact "0x" hex-string prefix the
            // Lean `hexFromBytes` serializer emits).
            assertGe(action.length, 2, "actionCbe has 0x prefix");
            assertGe(budget.length, 2, "recipientBudgetCbe has 0x prefix");
            assertEq(
                string(abi.encodePacked(action[0], action[1])), "0x", "actionCbe 0x prefix"
            );
            assertEq(
                string(abi.encodePacked(budget[0], budget[1])), "0x", "recipientBudgetCbe 0x prefix"
            );
            // 72 bytes => "0x" + 144 hex chars
            assertEq(action.length, 2 + 144, "actionCbe decodes to 72 bytes");
            // 18 bytes => "0x" + 36 hex chars
            assertEq(budget.length, 2 + 36, "recipientBudgetCbe decodes to 18 bytes");
        }
    }

    // ------------------------------------------------------------------
    // Helpers
    // ------------------------------------------------------------------

    /// @notice Deploy a BOLD-enabled bridge with the given ETH-leg and
    ///         BOLD-leg `weiPerBudgetUnit` rates; full `[0, 5000]` fee
    ///         range, no TVL ceiling, migration unset.  Requires a BOLD
    ///         mock etched at the pin (done in `setUp`).
    function _deployBridge(uint64 ethRate, uint64 boldRate)
        internal
        returns (KnomosisBridge)
    {
        uint64[] memory rids = new uint64[](0);
        address[] memory toks = new address[](0);
        return new KnomosisBridge(
            KnomosisBridge.ConstructorArgs({
                knomosisVersionTag: keccak256("knomosis-bold-deposit-crosscheck"),
                attestor: address(0xA11CE),
                disputeVerifier: address(0xDEAD),
                sequencerStake: address(0xBEEF),
                migration: address(0),
                disputeWindowBlocks: 100,
                maxRedemptionWindowBlocks: 50,
                maxAttestationStaleBlocks: 200,
                cooldownBlocks: 50,
                tvlCap: type(uint256).max,
                minFeeBps: 0,
                maxFeeBps: 5000,
                weiPerBudgetUnitEth: ethRate,
                weiPerBudgetUnitBold: boldRate,
                boldTokenAddress: BOLD,
                boldTvlCap: type(uint256).max,
                boldCircuitBreaker: BOLD_BREAKER,
                boldAdmin: BOLD_ADMIN,
                enableLiquityAutoCircuitTrigger: false,
                erc20ResourceIds: rids,
                erc20TokenAddrs: toks
            })
        );
    }

    /// @notice Deploy a BOLD-enabled bridge calibrated to `boldRate` (ETH
    ///         leg pinned at the minimum valid rate of 1).
    function _deployBoldBridge(uint64 boldRate) internal returns (KnomosisBridge) {
        return _deployBridge(1, boldRate);
    }

    /// @notice Locate + decode the single `DepositWithFeeInitiated` entry
    ///         in a recorded-log array (skips any BOLD `Transfer` event).
    function _decodeDepositWithFee(Vm.Log[] memory logs)
        internal
        pure
        returns (uint256 userAmount, uint256 poolAmount, uint64 budgetGrant)
    {
        bytes32 sig = keccak256(
            "DepositWithFeeInitiated(address,uint64,address,uint256,uint256,uint64,uint64,bytes32)"
        );
        for (uint256 i = 0; i < logs.length; i++) {
            if (logs[i].topics.length == 4 && logs[i].topics[0] == sig) {
                (userAmount, poolAmount, budgetGrant,,) =
                    abi.decode(logs[i].data, (uint256, uint256, uint64, uint64, bytes32));
                return (userAmount, poolAmount, budgetGrant);
            }
        }
        revert("DepositWithFeeInitiated not found");
    }
}
