// Canon  - A Societal Kernel
// Copyright (C) 2026  Adam Hall
// This program comes with ABSOLUTELY NO WARRANTY.
// This is free software, and you are welcome to redistribute it
// under certain conditions. See: https://github.com/hatter6822/Orbcrypt/blob/main/LICENSE

//! Cross-stack fixture-driven tests for `canon-hash-keccak256`.
//!
//! Loads `runtime/tests/cross-stack/keccak256.cxsf` (generated by
//! `examples/gen_keccak256_fixtures.rs`) and asserts that every
//! record's expected digest byte-equals `keccak256(input)`.  This
//! is the load-bearing cross-stack contract.

use canon_cross_stack::{FixtureFile, FixtureKind};
use canon_hash_keccak256::keccak256;
use std::path::PathBuf;

fn fixture_path() -> PathBuf {
    let mut p = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    p.pop();
    p.push("tests");
    p.push("cross-stack");
    p.push("keccak256.cxsf");
    p
}

#[test]
fn fixture_file_loads() {
    let p = fixture_path();
    let fixture = FixtureFile::load(&p).unwrap_or_else(|e| {
        panic!(
            "Fixture file not found or unreadable at {}: {e}.  Re-generate via \
             `cargo run --example gen_keccak256_fixtures` from the workspace root.",
            p.display()
        );
    });
    assert_eq!(fixture.kind(), FixtureKind::Hash);
    assert!(
        fixture.records().len() >= 30,
        "RH-A.2.d plan requires ≥ 30 fixture vectors; corpus has {}",
        fixture.records().len()
    );
}

#[test]
fn fixture_records_match_keccak256() {
    let p = fixture_path();
    let fixture = FixtureFile::load(&p).expect("fixture present");

    for (index, record) in fixture.records().iter().enumerate() {
        let actual = keccak256(&record.input);
        assert_eq!(
            record.expected.len(),
            32,
            "Record {index}: expected field length {} (must be 32 for keccak256)",
            record.expected.len()
        );
        assert_eq!(
            actual.as_slice(),
            record.expected.as_slice(),
            "Record {index}: hash mismatch.  input len={}, expected={:02x?}, actual={:02x?}",
            record.input.len(),
            record.expected,
            actual,
        );
    }
}

/// All records have the same 32-byte expected length (consistency
/// gate; defends against an off-by-one in the generator).
#[test]
fn all_records_have_32byte_digests() {
    let p = fixture_path();
    let fixture = FixtureFile::load(&p).expect("fixture present");
    for (index, record) in fixture.records().iter().enumerate() {
        assert_eq!(
            record.expected.len(),
            32,
            "Record {index}: expected field is {} bytes, must be 32",
            record.expected.len()
        );
    }
}
