// SPDX-License-Identifier: GPL-3.0-or-later
// Knomosis  - A Societal Kernel
// Copyright (C) 2026  Adam Hall
// This program comes with ABSOLUTELY NO WARRANTY.
// This is free software, and you are welcome to redistribute it
// under certain conditions. See: https://github.com/hatter6822/Knomosis/blob/main/LICENSE

//! WU GP.6.3 — Lean → Rust cross-stack differential for the `Event`
//! wire format.
//!
//! This is the genuine cross-stack verification the event-type
//! registry was previously missing: every `expectedCbe` field in
//! `event_subscribe_cbe.json` is the hex of LEAN's
//! `Encoding.Event.encode` (not a Rust self-encoding), so these
//! tests prove the registry's leading-tag assumption against REAL
//! Lean bytes for all 21 frozen constructors (tags 0..=20).
//!
//! For each fixture entry this asserts:
//!   * [`peek_event_tag`] reads exactly the entry's `tag` from the
//!     leading 9-byte CBE head of the real Lean payload, and
//!   * [`EventClass::classify`] resolves to `Known(EventType)` whose
//!     [`EventType::name`] equals the entry's canonical `kind`.
//!
//! The fixture is generated by
//! `LegalKernel/Test/Bridge/CrossCheck/EventCbe.lean` during
//! `lake test`.  A Lean encoder change drifts the committed JSON
//! (caught Lean-side by verify-mode and here once regenerated); a
//! Rust registry/peek bug fails these assertions.

use std::path::PathBuf;

use knomosis_event_subscribe::event_type::{
    peek_event_tag, EventClass, EventType, KNOWN_EVENT_TAG_COUNT,
};
use serde::Deserialize;

/// Pinned generator identifier.  A Lean-side version bump forces an
/// explicit update here, so the differential can never silently
/// consume a fixture from a different schema version.
const EXPECTED_FIXTURE_IDENTIFIER: &str = "knomosis-event-subscribe/event-cbe/v1";

/// Fixture header — mirrors the Lean generator's `header` object.
/// `deny_unknown_fields` rejects an unannounced Lean-side key.
#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
struct Header {
    /// Lean generator identifier; pinned by
    /// `lean_event_corpus_header_consistent`.
    identifier: String,
    /// Total entry count (== `entries.len()`).
    count: usize,
    /// The Lean-side frozen tag count; cross-checked against
    /// `KNOWN_EVENT_TAG_COUNT`.
    known_tag_count: u64,
    /// Informational; deserialised so `deny_unknown_fields` accepts
    /// the Lean JSON, value not asserted.
    #[allow(dead_code)]
    note: String,
}

/// One reference vector: a real Lean-encoded `Event`.
#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
struct Entry {
    /// Canonical lowerCamelCase constructor name (matches
    /// `EventType::name`).
    kind: String,
    /// The constructor's frozen wire tag.
    tag: u64,
    /// Diagnostic category ("canonical" / "gp-edge").
    category: String,
    /// `0x`-prefixed lowercase hex of Lean's `Event.encode` output.
    expected_cbe: String,
}

/// Top-level fixture.
#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct Fixture {
    header: Header,
    entries: Vec<Entry>,
}

/// Resolve `<repo>/solidity/test/CrossCheck/fixtures/event_subscribe_cbe.json`.
fn locate_fixture() -> Option<PathBuf> {
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    // <repo>/runtime/knomosis-event-subscribe -> <repo>
    let repo = manifest.parent()?.parent()?;
    let fixture = repo
        .join("solidity")
        .join("test")
        .join("CrossCheck")
        .join("fixtures")
        .join("event_subscribe_cbe.json");
    if fixture.exists() {
        Some(fixture)
    } else {
        None
    }
}

/// Load the fixture: panic on malformed/schema-drift, panic on
/// absence UNDER CI (the committed fixture must be present), skip
/// (`None`) locally on a fresh checkout that has not run `lake test`.
fn load_fixture() -> Option<Fixture> {
    let Some(path) = locate_fixture() else {
        assert!(
            std::env::var_os("CI").is_none(),
            "event_subscribe_cbe.json is absent under CI — the committed \
             cross-stack fixture MUST be present.  If a PR deleted or moved it, \
             restore it; otherwise regenerate via \
             `KNOMOSIS_FIXTURES_OVERWRITE=1 lake test`."
        );
        eprintln!("[SKIP] event_subscribe_cbe.json not found.  Run `lake test` to generate it.");
        return None;
    };
    let bytes = std::fs::read(&path)
        .unwrap_or_else(|e| panic!("fixture exists at {path:?} but cannot be read: {e}"));
    let fixture: Fixture = serde_json::from_slice(&bytes).unwrap_or_else(|e| {
        panic!(
            "fixture at {path:?} is malformed JSON or schema-drifted: {e}.  \
             Rebuild via `KNOMOSIS_FIXTURES_OVERWRITE=1 lake test`."
        )
    });
    Some(fixture)
}

/// Decode a `0x`-prefixed lowercase hex string to bytes.
fn decode_hex(s: &str) -> Vec<u8> {
    let stripped = s
        .strip_prefix("0x")
        .unwrap_or_else(|| panic!("expectedCbe is not 0x-prefixed: {s}"));
    hex::decode(stripped).unwrap_or_else(|e| panic!("expectedCbe is not valid hex ({s}): {e}"))
}

/// Header is consistent: identifier pinned, count matches, and the
/// Lean-side frozen tag count agrees with the Rust registry.
#[test]
fn lean_event_corpus_header_consistent() {
    let Some(fx) = load_fixture() else { return };
    assert_eq!(
        fx.header.identifier, EXPECTED_FIXTURE_IDENTIFIER,
        "fixture identifier drifted"
    );
    assert_eq!(
        fx.header.count,
        fx.entries.len(),
        "header count != number of entries"
    );
    assert_eq!(
        fx.header.known_tag_count, KNOWN_EVENT_TAG_COUNT,
        "Lean knownTagCount disagrees with Rust KNOWN_EVENT_TAG_COUNT — \
         the registries are out of sync"
    );
}

/// The load-bearing differential: for every real Lean-encoded event,
/// `peek_event_tag` reads exactly the entry's tag from the leading
/// 9-byte head.
#[test]
fn lean_event_peek_tag_matches_for_all_entries() {
    let Some(fx) = load_fixture() else { return };
    for e in &fx.entries {
        let bytes = decode_hex(&e.expected_cbe);
        let read = peek_event_tag(&bytes).unwrap_or_else(|err| {
            panic!(
                "peek_event_tag failed on real Lean bytes for {} ({}): {err}",
                e.kind, e.category
            )
        });
        assert_eq!(
            read, e.tag,
            "peek_event_tag read {read} from Lean bytes for {} ({}), expected tag {}",
            e.kind, e.category, e.tag
        );
    }
}

/// `classify` resolves every real Lean payload to `Known(EventType)`
/// whose `name()` equals the entry's canonical `kind`.
#[test]
fn lean_event_classify_known_matches_name() {
    let Some(fx) = load_fixture() else { return };
    for e in &fx.entries {
        let bytes = decode_hex(&e.expected_cbe);
        match EventClass::classify(&bytes) {
            EventClass::Known(ty) => {
                assert_eq!(
                    ty.tag(),
                    e.tag,
                    "classify tag mismatch for {} ({})",
                    e.kind,
                    e.category
                );
                assert_eq!(
                    ty.name(),
                    e.kind,
                    "classify name mismatch for tag {} ({})",
                    e.tag,
                    e.category
                );
            }
            other => panic!(
                "classify of real Lean bytes for {} ({}) was not Known: {other:?}",
                e.kind, e.category
            ),
        }
    }
}

/// The canonical entries cover all 20 known tags exactly once — a
/// sync gate: if Lean appends a constructor, this fails until the
/// fixture (and registry) catch up.
#[test]
fn lean_event_canonical_covers_all_known_tags() {
    let Some(fx) = load_fixture() else { return };
    let mut canonical_tags: Vec<u64> = fx
        .entries
        .iter()
        .filter(|e| e.category == "canonical")
        .map(|e| e.tag)
        .collect();
    canonical_tags.sort_unstable();
    let expected: Vec<u64> = (0..KNOWN_EVENT_TAG_COUNT).collect();
    assert_eq!(
        canonical_tags, expected,
        "canonical entries must cover tags 0..{KNOWN_EVENT_TAG_COUNT} exactly once"
    );
    // Every canonical tag resolves through the registry.
    for tag in &canonical_tags {
        assert!(
            EventType::from_tag(*tag).is_some(),
            "registry does not know canonical tag {tag}"
        );
    }
}

/// Gas-pool-family entries (tags 16..=19) classify as the gas-pool
/// family, across both canonical and edge-value categories.
#[test]
fn lean_event_gas_pool_family_classified() {
    let Some(fx) = load_fixture() else { return };
    let mut seen_gp = 0usize;
    for e in &fx.entries {
        let bytes = decode_hex(&e.expected_cbe);
        let class = EventClass::classify(&bytes);
        if (16..=20).contains(&e.tag) {
            assert!(
                class.is_gas_pool_family(),
                "tag {} ({}) should classify as gas-pool family",
                e.tag,
                e.category
            );
            seen_gp += 1;
        } else {
            assert!(
                !class.is_gas_pool_family(),
                "tag {} ({}) should NOT be gas-pool family",
                e.tag,
                e.category
            );
        }
    }
    assert!(
        seen_gp >= 4,
        "expected at least the 4 canonical GP-family entries"
    );
}
