// SPDX-License-Identifier: GPL-3.0-or-later
// Knomosis  - A Societal Kernel
// Copyright (C) 2026  Adam Hall
// This program comes with ABSOLUTELY NO WARRANTY.
// This is free software, and you are welcome to redistribute it
// under certain conditions. See: https://github.com/hatter6822/Knomosis/blob/main/LICENSE

//! True Lean → Rust CBE-encoder differential for the `Action.ammSwap`
//! constructor (WU GP.11.7).
//!
//! Loads `amm_swap.json` (generated by
//! `LegalKernel/Test/Bridge/CrossCheck/AmmSwap.lean`), reconstructs
//! each `Action::AmmSwap` from the numeric fields, runs the Rust
//! `encoding::encode_action`, and asserts byte-equality against the
//! Lean-sourced `expectedCbe`.
//!
//! Additionally verifies the AMM pricing function (`getAmountOut`),
//! k-monotonicity, and no-drain properties on each corpus entry.
//!
//! Hash-independent: no keccak-binding gate needed.

use std::path::PathBuf;

use knomosis_l1_ingest::action::Action;
use knomosis_l1_ingest::encoding::encode_action;
use serde::Deserialize;

const AMM_SWAP_FEE_BPS: u128 = 30;
const BPS_DENOMINATOR: u128 = 10000;

/// Fixture header.
#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
struct Header {
    workstream: String,
    count: usize,
    grid_count: usize,
    corner_count: usize,
    amm_swap_fee_bps: u64,
    bps_denominator: u64,
    amm_reserve_actor: u64,
    action_tag: u64,
}

/// One corpus entry.  Amount-scale fields and k-products are emitted as
/// 0x-prefixed 32-byte BE hex strings by the Lean generator.
#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
struct Entry {
    category: String,
    from_resource: u64,
    to_resource: u64,
    amount_in: String,
    reserve_in: String,
    reserve_out: String,
    fee_bps: u64,
    expected_out: String,
    min_amount_out: String,
    slippage_satisfied: bool,
    k_before: String,
    k_after: String,
    amm_reserve_actor: u64,
    expected_cbe: String,
}

/// Top-level fixture.
#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct Fixture {
    header: Header,
    entries: Vec<Entry>,
}

/// Parse a `0x`-prefixed hex string into a u128.  Panics if the value
/// exceeds u128::MAX.
fn parse_hex_u128(s: &str) -> u128 {
    let stripped = s
        .strip_prefix("0x")
        .unwrap_or_else(|| panic!("hex field is not 0x-prefixed: {s}"));
    u128::from_str_radix(stripped, 16)
        .unwrap_or_else(|e| panic!("hex field does not fit u128 ({s}): {e}"))
}

/// Parse a `0x`-prefixed hex string into a `[u8; 32]` big-endian byte
/// array, then interpret as a 256-bit unsigned integer.  Returns
/// `(high_u128, low_u128)` where the full value is `high << 128 | low`.
fn parse_hex_u256(s: &str) -> (u128, u128) {
    let stripped = s
        .strip_prefix("0x")
        .unwrap_or_else(|| panic!("hex field is not 0x-prefixed: {s}"));
    assert_eq!(
        stripped.len(),
        64,
        "expected 64 hex chars for u256, got {}: {s}",
        stripped.len()
    );
    let bytes = hex::decode(stripped).unwrap_or_else(|e| panic!("hex field is invalid ({s}): {e}"));
    assert_eq!(bytes.len(), 32);
    let high = u128::from_be_bytes(bytes[0..16].try_into().unwrap());
    let low = u128::from_be_bytes(bytes[16..32].try_into().unwrap());
    (high, low)
}

/// Compare two u256 values represented as `(high, low)` pairs.
/// Returns true if `a <= b`.
fn u256_le(a: (u128, u128), b: (u128, u128)) -> bool {
    a.0 < b.0 || (a.0 == b.0 && a.1 <= b.1)
}

/// Resolve the fixture path.
fn locate_fixture() -> Option<PathBuf> {
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let repo = manifest.parent()?.parent()?;
    let fixture = repo
        .join("solidity")
        .join("test")
        .join("CrossCheck")
        .join("fixtures")
        .join("amm_swap.json");
    if fixture.exists() {
        Some(fixture)
    } else {
        None
    }
}

fn load_fixture() -> Option<Fixture> {
    let Some(path) = locate_fixture() else {
        assert!(
            std::env::var_os("CI").is_none(),
            "amm_swap.json is absent under CI — the committed cross-stack fixture \
             MUST be present.  Regenerate via `KNOMOSIS_FIXTURES_OVERWRITE=1 lake test`."
        );
        return None;
    };
    let bytes = std::fs::read(&path)
        .unwrap_or_else(|e| panic!("fixture exists at {path:?} but cannot be read: {e}"));
    let fixture: Fixture = serde_json::from_slice(&bytes).unwrap_or_else(|e| {
        panic!(
            "fixture at {path:?} is malformed JSON or schema-drifted: {e}.  \
             Rebuild via `KNOMOSIS_FIXTURES_OVERWRITE=1 lake test`."
        )
    });
    Some(fixture)
}

fn decode_hex(s: &str) -> Vec<u8> {
    let stripped = s
        .strip_prefix("0x")
        .unwrap_or_else(|| panic!("expectedCbe is not 0x-prefixed: {s}"));
    hex::decode(stripped).unwrap_or_else(|e| panic!("expectedCbe is not valid hex ({s}): {e}"))
}

/// Rust mirror of the Lean `getAmountOut` pricing function.
/// Uses checked arithmetic to detect overflow.
fn get_amount_out(
    amount_in: u128,
    reserve_in: u128,
    reserve_out: u128,
    fee_bps: u128,
) -> Option<u128> {
    let amount_in_with_fee = amount_in.checked_mul(BPS_DENOMINATOR.checked_sub(fee_bps)?)?;
    let numerator = amount_in_with_fee.checked_mul(reserve_out)?;
    let denominator = reserve_in
        .checked_mul(BPS_DENOMINATOR)?
        .checked_add(amount_in_with_fee)?;
    if denominator == 0 {
        return Some(0);
    }
    Some(numerator / denominator)
}

/// Headline differential: every Lean-computed `expectedCbe` equals
/// the Rust `encode_action` output.
#[test]
fn amm_swap_corpus_byte_equivalence() {
    let Some(fixture) = load_fixture() else {
        eprintln!(
            "[SKIP] amm_swap.json not found.  Run `lake test` \
             (with KNOMOSIS_FIXTURES_OVERWRITE=1) to materialise."
        );
        return;
    };
    assert_eq!(
        fixture.header.count,
        fixture.entries.len(),
        "header count disagrees with entries length"
    );
    for (i, e) in fixture.entries.iter().enumerate() {
        let amount_in = parse_hex_u128(&e.amount_in);
        let expected_out = parse_hex_u128(&e.expected_out);
        let action = Action::AmmSwap {
            from_resource: e.from_resource,
            to_resource: e.to_resource,
            amount_in,
            amount_out: expected_out,
            amm_reserve_actor: e.amm_reserve_actor,
        };
        let actual = encode_action(&action).unwrap_or_else(|err| {
            panic!("entry {i} ({}): encode_action failed: {err:?}", e.category)
        });
        let expected = decode_hex(&e.expected_cbe);
        assert_eq!(
            actual, expected,
            "entry {i} ({}): Rust encode_action bytes differ from Lean Action.encode",
            e.category
        );
    }
}

/// Coverage: the fixture covers both grid and corner entries.
#[test]
fn amm_swap_corpus_coverage() {
    let Some(fixture) = load_fixture() else {
        eprintln!("[SKIP] amm_swap.json not found.");
        return;
    };
    assert_eq!(
        fixture.header.grid_count + fixture.header.corner_count,
        fixture.header.count,
        "grid + corner must equal total count"
    );
    assert!(
        fixture.header.grid_count >= 54,
        "grid should have >= 54 entries"
    );
    assert!(
        fixture.header.corner_count >= 10,
        "corner should have >= 10 entries"
    );
}

/// Every entry's leading tag byte is 0x17 (= 23, ammSwap's frozen index).
#[test]
fn amm_swap_corpus_tag_pin() {
    let Some(fixture) = load_fixture() else {
        eprintln!("[SKIP] amm_swap.json not found.");
        return;
    };
    for (i, e) in fixture.entries.iter().enumerate() {
        let amount_in = parse_hex_u128(&e.amount_in);
        let expected_out = parse_hex_u128(&e.expected_out);
        let action = Action::AmmSwap {
            from_resource: e.from_resource,
            to_resource: e.to_resource,
            amount_in,
            amount_out: expected_out,
            amm_reserve_actor: e.amm_reserve_actor,
        };
        assert_eq!(
            action.tag(),
            23,
            "entry {i} ({}): tag must be 23",
            e.category
        );
    }
}

/// Header constants match the Rust definitions.
#[test]
fn amm_swap_corpus_header_constants() {
    let Some(fixture) = load_fixture() else {
        eprintln!("[SKIP] amm_swap.json not found.");
        return;
    };
    assert_eq!(fixture.header.workstream, "GP.11.7");
    assert_eq!(fixture.header.amm_swap_fee_bps, AMM_SWAP_FEE_BPS as u64);
    assert_eq!(fixture.header.bps_denominator, BPS_DENOMINATOR as u64);
    assert_eq!(fixture.header.amm_reserve_actor, 3);
    assert_eq!(fixture.header.action_tag, 23);
}

/// Every entry's `expectedOut` matches the Rust `get_amount_out`
/// recomputation.  Entries whose intermediate products overflow u128
/// are skipped (the Lean/Solidity side uses unbounded/256-bit
/// arithmetic natively).
#[test]
fn amm_swap_corpus_formula_compliance() {
    let Some(fixture) = load_fixture() else {
        eprintln!("[SKIP] amm_swap.json not found.");
        return;
    };
    let mut checked = 0usize;
    for (i, e) in fixture.entries.iter().enumerate() {
        let amount_in = parse_hex_u128(&e.amount_in);
        let reserve_in = parse_hex_u128(&e.reserve_in);
        let reserve_out = parse_hex_u128(&e.reserve_out);
        let fee_bps = u128::from(e.fee_bps);
        let expected_out = parse_hex_u128(&e.expected_out);
        if let Some(recomputed) = get_amount_out(amount_in, reserve_in, reserve_out, fee_bps) {
            assert_eq!(
                expected_out, recomputed,
                "entry {i} ({}): formula mismatch (expected_out={}, recomputed={})",
                e.category, expected_out, recomputed
            );
            checked += 1;
        }
    }
    assert!(
        checked > fixture.entries.len() / 2,
        "fewer than half the entries were formula-checked ({checked}/{})",
        fixture.entries.len()
    );
}

/// No-drain: `expectedOut < reserveOut` for every valid entry.
#[test]
fn amm_swap_corpus_no_drain() {
    let Some(fixture) = load_fixture() else {
        eprintln!("[SKIP] amm_swap.json not found.");
        return;
    };
    for (i, e) in fixture.entries.iter().enumerate() {
        let amount_in = parse_hex_u128(&e.amount_in);
        let reserve_in = parse_hex_u128(&e.reserve_in);
        let reserve_out = parse_hex_u128(&e.reserve_out);
        let expected_out = parse_hex_u128(&e.expected_out);
        if reserve_in == 0
            || reserve_out == 0
            || amount_in == 0
            || e.fee_bps >= BPS_DENOMINATOR as u64
        {
            continue;
        }
        assert!(
            expected_out < reserve_out,
            "entry {i} ({}): no-drain violated ({} >= {})",
            e.category,
            expected_out,
            reserve_out
        );
    }
}

/// k-monotonicity: `kBefore <= kAfter` for every entry.  Values are
/// parsed as u256 (two u128 halves) since k-products can exceed u128.
#[test]
fn amm_swap_corpus_k_monotonicity() {
    let Some(fixture) = load_fixture() else {
        eprintln!("[SKIP] amm_swap.json not found.");
        return;
    };
    for (i, e) in fixture.entries.iter().enumerate() {
        let k_before = parse_hex_u256(&e.k_before);
        let k_after = parse_hex_u256(&e.k_after);
        assert!(
            u256_le(k_before, k_after),
            "entry {i} ({}): k decreased",
            e.category
        );
    }
}

/// slippageSatisfied is correctly computed.
#[test]
fn amm_swap_corpus_slippage() {
    let Some(fixture) = load_fixture() else {
        eprintln!("[SKIP] amm_swap.json not found.");
        return;
    };
    for (i, e) in fixture.entries.iter().enumerate() {
        let expected_out = parse_hex_u128(&e.expected_out);
        let min_amount_out = parse_hex_u128(&e.min_amount_out);
        let expected = expected_out >= min_amount_out;
        assert_eq!(
            e.slippage_satisfied, expected,
            "entry {i} ({}): slippage flag mismatch",
            e.category
        );
    }
}
