// SPDX-License-Identifier: GPL-3.0-or-later
// Knomosis  - A Societal Kernel
// Copyright (C) 2026  Adam Hall
// This program comes with ABSOLUTELY NO WARRANTY.
// This is free software, and you are welcome to redistribute it
// under certain conditions. See: https://github.com/hatter6822/Knomosis/blob/main/LICENSE

//! True Lean → Rust CBE-encoder differential for the `Action.ammSwap`
//! constructor (WU GP.11.7).
//!
//! Loads `amm_swap.json` (generated by
//! `LegalKernel/Test/Bridge/CrossCheck/AmmSwap.lean`), reconstructs
//! each `Action::AmmSwap` from the numeric fields, runs the Rust
//! `encoding::encode_action`, and asserts byte-equality against the
//! Lean-sourced `expectedCbe`.
//!
//! Additionally verifies the AMM pricing function (`getAmountOut`),
//! k-monotonicity, and no-drain properties on each corpus entry.
//!
//! Hash-independent: no keccak-binding gate needed.

use std::path::PathBuf;

use knomosis_l1_ingest::action::Action;
use knomosis_l1_ingest::encoding::encode_action;
use serde::Deserialize;

const AMM_SWAP_FEE_BPS: u128 = 30;
const BPS_DENOMINATOR: u128 = 10000;

/// Fixture header.
#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
struct Header {
    workstream: String,
    count: usize,
    grid_count: usize,
    corner_count: usize,
    amm_swap_fee_bps: u64,
    bps_denominator: u64,
    amm_reserve_actor: u64,
    action_tag: u64,
}

/// One corpus entry.  Amount-scale fields and k-products are emitted as
/// 0x-prefixed 32-byte BE hex strings by the Lean generator.
#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
struct Entry {
    category: String,
    from_resource: u64,
    to_resource: u64,
    amount_in: String,
    reserve_in: String,
    reserve_out: String,
    fee_bps: u64,
    expected_out: String,
    min_amount_out: String,
    slippage_satisfied: bool,
    k_before: String,
    k_after: String,
    new_reserve_in: String,
    new_reserve_out: String,
    reserve_actor_credit_from: String,
    reserve_actor_debit_to: String,
    amm_reserve_actor: u64,
    expected_cbe: String,
}

/// Top-level fixture.
#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct Fixture {
    header: Header,
    entries: Vec<Entry>,
}

/// Parse a `0x`-prefixed hex string into a u128.  Panics if the value
/// exceeds u128::MAX.
fn parse_hex_u128(s: &str) -> u128 {
    let stripped = s
        .strip_prefix("0x")
        .unwrap_or_else(|| panic!("hex field is not 0x-prefixed: {s}"));
    u128::from_str_radix(stripped, 16)
        .unwrap_or_else(|e| panic!("hex field does not fit u128 ({s}): {e}"))
}

/// Parse a `0x`-prefixed hex string into a `[u8; 32]` big-endian byte
/// array, then interpret as a 256-bit unsigned integer.  Returns
/// `(high_u128, low_u128)` where the full value is `high << 128 | low`.
fn parse_hex_u256(s: &str) -> (u128, u128) {
    let stripped = s
        .strip_prefix("0x")
        .unwrap_or_else(|| panic!("hex field is not 0x-prefixed: {s}"));
    assert_eq!(
        stripped.len(),
        64,
        "expected 64 hex chars for u256, got {}: {s}",
        stripped.len()
    );
    let bytes = hex::decode(stripped).unwrap_or_else(|e| panic!("hex field is invalid ({s}): {e}"));
    assert_eq!(bytes.len(), 32);
    let high = u128::from_be_bytes(bytes[0..16].try_into().unwrap());
    let low = u128::from_be_bytes(bytes[16..32].try_into().unwrap());
    (high, low)
}

/// Compare two u256 values represented as `(high, low)` pairs.
/// Returns true if `a <= b`.
fn u256_le(a: (u128, u128), b: (u128, u128)) -> bool {
    a.0 < b.0 || (a.0 == b.0 && a.1 <= b.1)
}

/// Resolve the fixture path.
fn locate_fixture() -> Option<PathBuf> {
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let repo = manifest.parent()?.parent()?;
    let fixture = repo
        .join("solidity")
        .join("test")
        .join("CrossCheck")
        .join("fixtures")
        .join("amm_swap.json");
    if fixture.exists() {
        Some(fixture)
    } else {
        None
    }
}

fn load_fixture() -> Option<Fixture> {
    let Some(path) = locate_fixture() else {
        assert!(
            std::env::var_os("CI").is_none(),
            "amm_swap.json is absent under CI — the committed cross-stack fixture \
             MUST be present.  Regenerate via `KNOMOSIS_FIXTURES_OVERWRITE=1 lake test`."
        );
        return None;
    };
    let bytes = std::fs::read(&path)
        .unwrap_or_else(|e| panic!("fixture exists at {path:?} but cannot be read: {e}"));
    let fixture: Fixture = serde_json::from_slice(&bytes).unwrap_or_else(|e| {
        panic!(
            "fixture at {path:?} is malformed JSON or schema-drifted: {e}.  \
             Rebuild via `KNOMOSIS_FIXTURES_OVERWRITE=1 lake test`."
        )
    });
    Some(fixture)
}

fn decode_hex(s: &str) -> Vec<u8> {
    let stripped = s
        .strip_prefix("0x")
        .unwrap_or_else(|| panic!("expectedCbe is not 0x-prefixed: {s}"));
    hex::decode(stripped).unwrap_or_else(|e| panic!("expectedCbe is not valid hex ({s}): {e}"))
}

/// Multiply two u128 values, returning a u256 as `(high, low)`.
fn mul_wide(a: u128, b: u128) -> (u128, u128) {
    let a_lo = a & 0xFFFF_FFFF_FFFF_FFFF;
    let a_hi = a >> 64;
    let b_lo = b & 0xFFFF_FFFF_FFFF_FFFF;
    let b_hi = b >> 64;
    let ll = a_lo * b_lo;
    let lh = a_lo * b_hi;
    let hl = a_hi * b_lo;
    let hh = a_hi * b_hi;
    let mid = (ll >> 64) + (lh & 0xFFFF_FFFF_FFFF_FFFF) + (hl & 0xFFFF_FFFF_FFFF_FFFF);
    let low = (ll & 0xFFFF_FFFF_FFFF_FFFF) | ((mid & 0xFFFF_FFFF_FFFF_FFFF) << 64);
    let high = hh + (lh >> 64) + (hl >> 64) + (mid >> 64);
    (high, low)
}

/// Divide a u256 `(high, low)` by a u128 divisor, returning a u128
/// quotient.  Panics if the quotient exceeds u128 or the divisor is 0.
fn div_u256_by_u128(num: (u128, u128), den: u128) -> u128 {
    assert!(den != 0, "division by zero");
    if num.0 == 0 {
        return num.1 / den;
    }
    let mut rem: u128 = 0;
    let mut quot: u128 = 0;
    let bits = 256u32;
    for i in (0..bits).rev() {
        rem <<= 1;
        let bit = if i >= 128 {
            (num.0 >> (i - 128)) & 1
        } else {
            (num.1 >> i) & 1
        };
        rem |= bit;
        if rem >= den {
            rem -= den;
            if i < 128 {
                quot |= 1u128 << i;
            } else {
                panic!("quotient exceeds u128");
            }
        }
    }
    quot
}

/// Rust mirror of the Lean `getAmountOut` pricing function.
/// Uses u256 intermediates via `mul_wide` / `div_u256_by_u128` so it
/// never overflows on corpus-range values.
fn get_amount_out_wide(
    amount_in: u128,
    reserve_in: u128,
    reserve_out: u128,
    fee_bps: u128,
) -> u128 {
    let factor = BPS_DENOMINATOR - fee_bps;
    let amount_in_with_fee = amount_in * factor;
    let numerator = mul_wide(amount_in_with_fee, reserve_out);
    let denom_base = reserve_in * BPS_DENOMINATOR;
    let denominator = denom_base + amount_in_with_fee;
    if denominator == 0 {
        return 0;
    }
    div_u256_by_u128(numerator, denominator)
}

/// Headline differential: every Lean-computed `expectedCbe` equals
/// the Rust `encode_action` output.
#[test]
fn amm_swap_corpus_byte_equivalence() {
    let Some(fixture) = load_fixture() else {
        eprintln!(
            "[SKIP] amm_swap.json not found.  Run `lake test` \
             (with KNOMOSIS_FIXTURES_OVERWRITE=1) to materialise."
        );
        return;
    };
    assert_eq!(
        fixture.header.count,
        fixture.entries.len(),
        "header count disagrees with entries length"
    );
    for (i, e) in fixture.entries.iter().enumerate() {
        let amount_in = parse_hex_u128(&e.amount_in);
        let expected_out = parse_hex_u128(&e.expected_out);
        let action = Action::AmmSwap {
            from_resource: e.from_resource,
            to_resource: e.to_resource,
            amount_in,
            amount_out: expected_out,
            amm_reserve_actor: e.amm_reserve_actor,
        };
        let actual = encode_action(&action).unwrap_or_else(|err| {
            panic!("entry {i} ({}): encode_action failed: {err:?}", e.category)
        });
        let expected = decode_hex(&e.expected_cbe);
        assert_eq!(
            actual, expected,
            "entry {i} ({}): Rust encode_action bytes differ from Lean Action.encode",
            e.category
        );
    }
}

/// Coverage: the fixture covers both grid and corner entries.
#[test]
fn amm_swap_corpus_coverage() {
    let Some(fixture) = load_fixture() else {
        eprintln!("[SKIP] amm_swap.json not found.");
        return;
    };
    assert_eq!(
        fixture.header.grid_count + fixture.header.corner_count,
        fixture.header.count,
        "grid + corner must equal total count"
    );
    assert!(
        fixture.header.grid_count >= 54,
        "grid should have >= 54 entries"
    );
    assert!(
        fixture.header.corner_count >= 10,
        "corner should have >= 10 entries"
    );
}

/// Every entry's leading tag byte is 0x17 (= 23, ammSwap's frozen index).
#[test]
fn amm_swap_corpus_tag_pin() {
    let Some(fixture) = load_fixture() else {
        eprintln!("[SKIP] amm_swap.json not found.");
        return;
    };
    for (i, e) in fixture.entries.iter().enumerate() {
        let amount_in = parse_hex_u128(&e.amount_in);
        let expected_out = parse_hex_u128(&e.expected_out);
        let action = Action::AmmSwap {
            from_resource: e.from_resource,
            to_resource: e.to_resource,
            amount_in,
            amount_out: expected_out,
            amm_reserve_actor: e.amm_reserve_actor,
        };
        assert_eq!(
            action.tag(),
            23,
            "entry {i} ({}): tag must be 23",
            e.category
        );
    }
}

/// Header constants match the Rust definitions.
#[test]
fn amm_swap_corpus_header_constants() {
    let Some(fixture) = load_fixture() else {
        eprintln!("[SKIP] amm_swap.json not found.");
        return;
    };
    assert_eq!(fixture.header.workstream, "GP.11.7");
    assert_eq!(fixture.header.amm_swap_fee_bps, AMM_SWAP_FEE_BPS as u64);
    assert_eq!(fixture.header.bps_denominator, BPS_DENOMINATOR as u64);
    assert_eq!(fixture.header.amm_reserve_actor, 3);
    assert_eq!(fixture.header.action_tag, 23);
}

/// Every entry's `expectedOut` matches the Rust `get_amount_out_wide`
/// recomputation using u256 intermediates — 100% coverage.
#[test]
fn amm_swap_corpus_formula_compliance() {
    let Some(fixture) = load_fixture() else {
        eprintln!("[SKIP] amm_swap.json not found.");
        return;
    };
    for (i, e) in fixture.entries.iter().enumerate() {
        let amount_in = parse_hex_u128(&e.amount_in);
        let reserve_in = parse_hex_u128(&e.reserve_in);
        let reserve_out = parse_hex_u128(&e.reserve_out);
        let fee_bps = u128::from(e.fee_bps);
        let expected_out = parse_hex_u128(&e.expected_out);
        let recomputed = get_amount_out_wide(amount_in, reserve_in, reserve_out, fee_bps);
        assert_eq!(
            expected_out, recomputed,
            "entry {i} ({}): formula mismatch (expected_out={expected_out}, recomputed={recomputed})",
            e.category,
        );
    }
}

/// No-drain: `expectedOut < reserveOut` for every valid entry.
#[test]
fn amm_swap_corpus_no_drain() {
    let Some(fixture) = load_fixture() else {
        eprintln!("[SKIP] amm_swap.json not found.");
        return;
    };
    for (i, e) in fixture.entries.iter().enumerate() {
        let amount_in = parse_hex_u128(&e.amount_in);
        let reserve_in = parse_hex_u128(&e.reserve_in);
        let reserve_out = parse_hex_u128(&e.reserve_out);
        let expected_out = parse_hex_u128(&e.expected_out);
        if reserve_in == 0
            || reserve_out == 0
            || amount_in == 0
            || e.fee_bps >= BPS_DENOMINATOR as u64
        {
            continue;
        }
        assert!(
            expected_out < reserve_out,
            "entry {i} ({}): no-drain violated ({} >= {})",
            e.category,
            expected_out,
            reserve_out
        );
    }
}

/// k-monotonicity: `kBefore <= kAfter` for every entry.  Values are
/// parsed as u256 (two u128 halves) since k-products can exceed u128.
#[test]
fn amm_swap_corpus_k_monotonicity() {
    let Some(fixture) = load_fixture() else {
        eprintln!("[SKIP] amm_swap.json not found.");
        return;
    };
    for (i, e) in fixture.entries.iter().enumerate() {
        let k_before = parse_hex_u256(&e.k_before);
        let k_after = parse_hex_u256(&e.k_after);
        assert!(
            u256_le(k_before, k_after),
            "entry {i} ({}): k decreased",
            e.category
        );
    }
}

/// slippageSatisfied is correctly computed.
#[test]
fn amm_swap_corpus_slippage() {
    let Some(fixture) = load_fixture() else {
        eprintln!("[SKIP] amm_swap.json not found.");
        return;
    };
    for (i, e) in fixture.entries.iter().enumerate() {
        let expected_out = parse_hex_u128(&e.expected_out);
        let min_amount_out = parse_hex_u128(&e.min_amount_out);
        let expected = expected_out >= min_amount_out;
        assert_eq!(
            e.slippage_satisfied, expected,
            "entry {i} ({}): slippage flag mismatch",
            e.category
        );
    }
}

/// Post-swap reserves match `reserveIn + amountIn` / `reserveOut - expectedOut`.
#[test]
fn amm_swap_corpus_post_swap_reserves() {
    let Some(fixture) = load_fixture() else {
        eprintln!("[SKIP] amm_swap.json not found.");
        return;
    };
    for (i, e) in fixture.entries.iter().enumerate() {
        let amount_in = parse_hex_u128(&e.amount_in);
        let reserve_in = parse_hex_u128(&e.reserve_in);
        let reserve_out = parse_hex_u128(&e.reserve_out);
        let expected_out = parse_hex_u128(&e.expected_out);
        let new_reserve_in = parse_hex_u128(&e.new_reserve_in);
        let new_reserve_out = parse_hex_u128(&e.new_reserve_out);
        assert_eq!(
            new_reserve_in,
            reserve_in + amount_in,
            "entry {i} ({}): newReserveIn mismatch",
            e.category
        );
        assert_eq!(
            new_reserve_out,
            reserve_out - expected_out,
            "entry {i} ({}): newReserveOut mismatch",
            e.category
        );
    }
}

/// L2 balance deltas on `ammReserveActor`: credit = amountIn, debit = expectedOut.
#[test]
fn amm_swap_corpus_l2_balance_deltas() {
    let Some(fixture) = load_fixture() else {
        eprintln!("[SKIP] amm_swap.json not found.");
        return;
    };
    for (i, e) in fixture.entries.iter().enumerate() {
        let amount_in = parse_hex_u128(&e.amount_in);
        let expected_out = parse_hex_u128(&e.expected_out);
        let credit = parse_hex_u128(&e.reserve_actor_credit_from);
        let debit = parse_hex_u128(&e.reserve_actor_debit_to);
        assert_eq!(
            credit, amount_in,
            "entry {i} ({}): reserveActorCreditFrom != amountIn",
            e.category
        );
        assert_eq!(
            debit, expected_out,
            "entry {i} ({}): reserveActorDebitTo != expectedOut",
            e.category
        );
    }
}

/// CXSF binary corpus loads with the correct kind and record count.
#[test]
fn amm_swap_cxsf_consumer() {
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let repo = manifest
        .parent()
        .and_then(|p| p.parent())
        .expect("repo root");
    let cxsf_path = repo.join("runtime/tests/cross-stack/amm_swap.cxsf");
    if !cxsf_path.exists() {
        assert!(
            std::env::var_os("CI").is_none(),
            "amm_swap.cxsf is absent under CI"
        );
        eprintln!("[SKIP] amm_swap.cxsf not found.");
        return;
    }
    let fixture = knomosis_cross_stack::FixtureFile::load(&cxsf_path)
        .unwrap_or_else(|e| panic!("failed to load amm_swap.cxsf: {e}"));
    assert_eq!(
        fixture.kind(),
        knomosis_cross_stack::FixtureKind::AmmSwap,
        "CXSF kind tag must be AmmSwap"
    );
    let records = fixture.records();
    assert!(
        records.len() >= 71,
        "CXSF should have >= 71 records, got {}",
        records.len()
    );
    for (i, rec) in records.iter().enumerate() {
        assert_eq!(
            rec.input.len(),
            40,
            "record {i}: input should be 40 bytes (5 × 8 BE u64)"
        );
        assert_eq!(
            rec.expected.len(),
            54,
            "record {i}: expected should be 54 bytes (Action.ammSwap CBE)"
        );
    }
}

/// CXSF-JSON content cross-check: the CXSF binary corpus's `expected`
/// bytes MUST equal the JSON corpus's `expectedCbe` for every record.
#[test]
fn amm_swap_cxsf_matches_json() {
    let Some(fixture) = load_fixture() else {
        eprintln!("[SKIP] amm_swap.json not found.");
        return;
    };
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let repo = manifest
        .parent()
        .and_then(|p| p.parent())
        .expect("repo root");
    let cxsf_path = repo.join("runtime/tests/cross-stack/amm_swap.cxsf");
    if !cxsf_path.exists() {
        eprintln!("[SKIP] amm_swap.cxsf not found.");
        return;
    }
    let cxsf = knomosis_cross_stack::FixtureFile::load(&cxsf_path)
        .unwrap_or_else(|e| panic!("failed to load amm_swap.cxsf: {e}"));
    let records = cxsf.records();
    assert_eq!(
        records.len(),
        fixture.entries.len(),
        "CXSF record count must equal JSON entry count"
    );
    for (i, (rec, entry)) in records.iter().zip(fixture.entries.iter()).enumerate() {
        let json_cbe = decode_hex(&entry.expected_cbe);
        assert_eq!(
            rec.expected, json_cbe,
            "record {i} ({}): CXSF expected bytes differ from JSON expectedCbe",
            entry.category
        );
        assert_eq!(
            rec.expected[0], 0x00,
            "record {i} ({}): first byte must be 0x00 (CBE Nat type)",
            entry.category
        );
        assert_eq!(
            rec.expected[1], 0x17,
            "record {i} ({}): second byte must be 0x17 (= 23, ammSwap tag LE)",
            entry.category
        );
    }
}

/// `mul_wide` known-vector unit tests (hand-computed).
#[test]
fn mul_wide_known_vectors() {
    assert_eq!(mul_wide(0, 0), (0, 0));
    assert_eq!(mul_wide(1, 1), (0, 1));
    assert_eq!(mul_wide(0, u128::MAX), (0, 0));
    assert_eq!(mul_wide(u128::MAX, 0), (0, 0));
    assert_eq!(mul_wide(1, u128::MAX), (0, u128::MAX));
    assert_eq!(mul_wide(u128::MAX, 1), (0, u128::MAX));
    // 2 * u128::MAX = 2^129 - 2 = (1, u128::MAX - 1)
    assert_eq!(mul_wide(2, u128::MAX), (1, u128::MAX - 1));
    assert_eq!(mul_wide(u128::MAX, 2), (1, u128::MAX - 1));
    // u128::MAX * u128::MAX = (2^128-1)^2 = 2^256 - 2^129 + 1
    //   high = u128::MAX - 1, low = 1
    assert_eq!(mul_wide(u128::MAX, u128::MAX), (u128::MAX - 1, 1));
    // 2^64 * 2^64 = 2^128 = (1, 0)
    let two_64: u128 = 1u128 << 64;
    assert_eq!(mul_wide(two_64, two_64), (1, 0));
    // 10^18 * 10^18 = 10^36
    let e18: u128 = 1_000_000_000_000_000_000;
    let product = e18 as u128 * e18 as u128; // fits in u128
    assert_eq!(mul_wide(e18, e18), (0, product));
    // (2^64-1) * (2^64-1) = 2^128 - 2^65 + 1 = (0, u128::MAX - 2*(2^64) + 2)
    let m64 = u64::MAX as u128;
    let expected_low = m64 * m64;
    assert_eq!(mul_wide(m64, m64), (0, expected_low));
}

/// `div_u256_by_u128` known-vector unit tests (hand-computed).
#[test]
fn div_u256_by_u128_known_vectors() {
    assert_eq!(div_u256_by_u128((0, 0), 1), 0);
    assert_eq!(div_u256_by_u128((0, 1), 1), 1);
    assert_eq!(div_u256_by_u128((0, 100), 10), 10);
    assert_eq!(div_u256_by_u128((0, u128::MAX), 1), u128::MAX);
    assert_eq!(div_u256_by_u128((0, u128::MAX), u128::MAX), 1);
    // (1, 0) = 2^128 / 2 = 2^127
    assert_eq!(div_u256_by_u128((1, 0), 2), 1u128 << 127);
    // (1, 0) = 2^128 / 2^128 = 1 — but 2^128 > u128::MAX, so den must be u128
    // Instead: (1, 0) / (2^64) = 2^128 / 2^64 = 2^64
    let two_64: u128 = 1u128 << 64;
    assert_eq!(div_u256_by_u128((1, 0), two_64), two_64);
    // mul_wide(a, b) / b == a  for non-zero b (round-trip)
    let a: u128 = 999_999_999_999_999;
    let b: u128 = 1_000_000_000_000_000_000;
    let product = mul_wide(a, b);
    assert_eq!(div_u256_by_u128(product, b), a);
    // mul_wide(u64::MAX, u64::MAX) / u64::MAX == u64::MAX (round-trip)
    let m64 = u64::MAX as u128;
    let product = mul_wide(m64, m64);
    assert_eq!(div_u256_by_u128(product, m64), m64);
    // floor division: (0, 7) / 3 == 2
    assert_eq!(div_u256_by_u128((0, 7), 3), 2);
    // (0, 10^36) / 10^18 = 10^18
    let e18: u128 = 1_000_000_000_000_000_000;
    let e36: u128 = e18 * e18;
    assert_eq!(div_u256_by_u128((0, e36), e18), e18);
}

/// `get_amount_out_wide` matches expected values for canonical hand vectors.
#[test]
fn get_amount_out_wide_known_vectors() {
    assert_eq!(get_amount_out_wide(1000, 1000, 1000, 0), 500);
    assert_eq!(get_amount_out_wide(1000, 1000, 1000, 30), 499);
    assert_eq!(get_amount_out_wide(0, 1000, 1000, 30), 0);
    // reserve_in = 0: denominator = amountIn*(10000-fee), output = reserveOut
    assert_eq!(get_amount_out_wide(1000, 0, 1000, 30), 1000);
    // Both denominator factors zero → denominator = 0 → returns 0
    assert_eq!(get_amount_out_wide(0, 0, 1000, 30), 0);
}
