-- SPDX-License-Identifier: GPL-3.0-or-later
/-
  Knomosis  - A Societal Kernel
  Copyright (C) 2026  Adam Hall
  This program comes with ABSOLUTELY NO WARRANTY.
  This is free software, and you are welcome to redistribute it
  under certain conditions. See: https://github.com/hatter6822/Knomosis/blob/main/LICENSE
-/

/-
LegalKernel.FaultProof.StateCellsInjective — the SMT state root
determines the state's cells.

## What this is for

`smtRootListAux_perm_of_eq_under_collision_free` (SmtInjective)
says equal SMT roots imply the *entry lists* are permutations.
`commitExtendedState` builds its entry list from an
`ExtendedState`, so composing the two gives the property the
fault-proof game actually needs: two states behind the same
published root agree on every cell a proof can open.

That composition is the EI.8 replacement.  The seven-component
`commitExtendedState` proves extensional equality by decomposing a
concatenation; a cell root cannot, so this is stated and proved on
its own terms rather than adapted.

## Why the conclusion is about cells

`ExtendedState.extEq` is not the right target and could not be
reached even in principle.  `State.Equiv` quantifies over *outer-map
membership* (`r ∈ s₁.balances ↔ r ∈ s₂.balances`), while a balance
cell reads `getBalance`, which defaults an absent entry to `0`.  A
resource present with an all-zero balance map and a resource absent
entirely are `State.Equiv`-distinct and cell-indistinguishable —
correctly so, because nothing a step can observe separates them.

The honest statement is therefore behavioural: every cell reads the
same on both sides.  That is exactly the interface the step VM has,
so it is also exactly what the game needs.
-/

import LegalKernel.FaultProof.SmtInjective
import LegalKernel.FaultProof.StateCells

set_option maxRecDepth 8192

namespace LegalKernel
namespace FaultProof

open LegalKernel.Authority
open LegalKernel.Bridge
open LegalKernel.Encoding
open LegalKernel.Runtime

/-! ## A `Pairwise` lemma for `flatMap`

The balance enumeration is a `flatMap` over the outer resource map,
and core has `Pairwise` lemmas for `append` and `map` but not for
`flatMap`.  This is the missing one. -/

/-- `Pairwise` over a `flatMap`: each produced block is internally
    pairwise, and any two elements from blocks generated by
    `S`-related sources are related. -/
theorem pairwise_flatMap {α β : Type} {R : β → β → Prop} {S : α → α → Prop}
    {l : List α} {f : α → List β}
    (h_in : ∀ a ∈ l, (f a).Pairwise R)
    (h_cross : ∀ a b, S a b → ∀ x ∈ f a, ∀ y ∈ f b, R x y)
    (h_l : l.Pairwise S) :
    (l.flatMap f).Pairwise R := by
  induction l with
  | nil => simp
  | cons a t ih =>
    rw [List.flatMap_cons]
    obtain ⟨h_head, h_tail⟩ := List.pairwise_cons.mp h_l
    refine List.pairwise_append.mpr
      ⟨h_in a (by simp), ih (fun b hb => h_in b (by simp [hb])) h_tail, ?_⟩
    intro x hx y hy
    obtain ⟨b, hb, hyb⟩ := List.mem_flatMap.mp hy
    exact h_cross a b (h_head b hb) x hx y hyb

/-! ## The tag enumeration is duplicate-free

`smtRootListAux` collapses a level holding two entries with equal
keys, so a repeated cell would silently vanish from the root.  The
enumeration must therefore be duplicate-free before any injectivity
statement about the root can be applied to it. -/

/-- Distinct kind indices give distinct tags. -/
private theorem ne_of_kindIndex_ne {a b : CellTag}
    (h : a.kindIndex ≠ b.kindIndex) : a ≠ b :=
  fun h_eq => h (by rw [h_eq])

/-- Every tag produced by a constant-kind constructor carries that
    kind index. -/
private theorem kindIndex_of_mem_map {α : Type} (f : α → CellTag) (k : Nat)
    (h : ∀ x, (f x).kindIndex = k) (l : List α) :
    ∀ t ∈ l.map f, t.kindIndex = k := by
  intro t ht
  obtain ⟨x, _, rfl⟩ := List.mem_map.mp ht
  exact h x

/-- The keys of a `TreeMap`'s `toList` are pairwise distinct. -/
theorem treeMap_toList_keys_pairwise_ne {α β : Type} [Ord α]
    [Std.TransCmp (compare (α := α))] [Std.LawfulEqCmp (compare (α := α))]
    (m : Std.TreeMap α β compare) :
    m.toList.Pairwise (fun a b => a.1 ≠ b.1) := by
  refine List.Pairwise.imp_of_mem ?_ Std.TreeMap.distinct_keys_toList
  intro a b _ _ h h_eq
  exact h (by rw [h_eq]; exact Std.compare_self)

/-- The seven keyed blocks of `stateCellTags`, each internally
    duplicate-free.  Stated one per block so the assembly below is a
    sequence of `pairwise_append` steps rather than one opaque
    tactic. -/
theorem stateCellTags_nodup (es : ExtendedState) :
    (stateCellTags es).Pairwise (· ≠ ·) := by
  -- Per-block kind indices, used for every cross-block obligation.
  have k_bal : ∀ t ∈ (es.base.balances.toList.flatMap (fun rbm =>
      rbm.2.toList.map (fun av => CellTag.balance rbm.1 av.1))), t.kindIndex = 0 := by
    intro t ht
    obtain ⟨rbm, _, ht'⟩ := List.mem_flatMap.mp ht
    obtain ⟨_, _, rfl⟩ := List.mem_map.mp ht'
    rfl
  have k_nonce := kindIndex_of_mem_map (fun an : ActorId × Nonce => CellTag.nonce an.1)
    1 (fun _ => rfl) es.nonces.next.toList
  have k_reg := kindIndex_of_mem_map (fun ak : ActorId × PublicKey => CellTag.registry ak.1)
    2 (fun _ => rfl) es.registry.toList
  have k_lp := kindIndex_of_mem_map
    (fun ap : ActorId × LocalPolicy => CellTag.localPolicy ap.1)
    3 (fun _ => rfl) es.localPolicies.toList
  have k_cons := kindIndex_of_mem_map
    (fun dr : DepositId × DepositRecord => CellTag.bridgeConsumed dr.1)
    4 (fun _ => rfl) es.bridge.consumed.toList
  have k_pend := kindIndex_of_mem_map
    (fun wp : WithdrawalId × PendingWithdrawal => CellTag.bridgePending wp.1)
    5 (fun _ => rfl) es.bridge.pending.toList
  have k_eb := kindIndex_of_mem_map
    (fun ab : ActorId × ActorBudget => CellTag.epochBudget ab.1)
    13 (fun _ => rfl) es.epochBudgets.toList
  have k_single : ∀ t ∈ singletonCellTags, 6 ≤ t.kindIndex ∧ t.kindIndex ≠ 13 := by
    decide
  -- Per-block internal distinctness.
  have p_bal : (es.base.balances.toList.flatMap (fun rbm =>
      rbm.2.toList.map (fun av => CellTag.balance rbm.1 av.1))).Pairwise (· ≠ ·) := by
    refine pairwise_flatMap ?_ ?_ (treeMap_toList_keys_pairwise_ne es.base.balances)
    · intro rbm _
      refine List.Pairwise.map _ ?_ (treeMap_toList_keys_pairwise_ne rbm.2)
      intro a b h h_eq
      exact h (by injection h_eq)
    · intro a b h_ne x hx y hy
      obtain ⟨_, _, rfl⟩ := List.mem_map.mp hx
      obtain ⟨_, _, rfl⟩ := List.mem_map.mp hy
      intro h_eq
      exact h_ne (by injection h_eq)
  have p_map : ∀ {α : Type} [Ord α] [Std.TransCmp (compare (α := α))]
      [Std.LawfulEqCmp (compare (α := α))] {β : Type}
      (m : Std.TreeMap α β compare) (f : α → CellTag),
      (∀ a b, f a = f b → a = b) →
      (m.toList.map (fun p => f p.1)).Pairwise (· ≠ ·) := by
    intro _ _ _ _ _ m f h_inj
    refine List.Pairwise.map _ ?_ (treeMap_toList_keys_pairwise_ne m)
    intro a b h h_eq
    exact h (h_inj _ _ h_eq)
  -- Assemble, left-associated, one `pairwise_append` per join.
  unfold stateCellTags
  refine List.pairwise_append.mpr ⟨?_, by decide, ?_⟩
  · refine List.pairwise_append.mpr ⟨?_, p_map es.epochBudgets CellTag.epochBudget
      (fun _ _ h => by injection h), ?_⟩
    · refine List.pairwise_append.mpr ⟨?_, p_map es.bridge.pending CellTag.bridgePending
        (fun _ _ h => by injection h), ?_⟩
      · refine List.pairwise_append.mpr ⟨?_, p_map es.bridge.consumed CellTag.bridgeConsumed
          (fun _ _ h => by injection h), ?_⟩
        · refine List.pairwise_append.mpr ⟨?_, p_map es.localPolicies CellTag.localPolicy
            (fun _ _ h => by injection h), ?_⟩
          · refine List.pairwise_append.mpr ⟨?_, p_map es.registry CellTag.registry
              (fun _ _ h => by injection h), ?_⟩
            · exact List.pairwise_append.mpr ⟨p_bal,
                p_map es.nonces.next CellTag.nonce (fun _ _ h => by injection h),
                fun a ha b hb => ne_of_kindIndex_ne (by rw [k_bal a ha, k_nonce b hb]; decide)⟩
            · intro a ha b hb
              rcases List.mem_append.mp ha with ha' | ha'
              · exact ne_of_kindIndex_ne (by rw [k_bal a ha', k_reg b hb]; decide)
              · exact ne_of_kindIndex_ne (by rw [k_nonce a ha', k_reg b hb]; decide)
          · intro a ha b hb
            rcases List.mem_append.mp ha with ha' | ha'
            · rcases List.mem_append.mp ha' with ha'' | ha''
              · exact ne_of_kindIndex_ne (by rw [k_bal a ha'', k_lp b hb]; decide)
              · exact ne_of_kindIndex_ne (by rw [k_nonce a ha'', k_lp b hb]; decide)
            · exact ne_of_kindIndex_ne (by rw [k_reg a ha', k_lp b hb]; decide)
        · intro a ha b hb
          refine ne_of_kindIndex_ne ?_
          rw [k_cons b hb]
          rcases List.mem_append.mp ha with ha' | ha'
          · rcases List.mem_append.mp ha' with ha'' | ha''
            · rcases List.mem_append.mp ha'' with h3 | h3
              · rw [k_bal a h3]; decide
              · rw [k_nonce a h3]; decide
            · rw [k_reg a ha'']; decide
          · rw [k_lp a ha']; decide
      · intro a ha b hb
        refine ne_of_kindIndex_ne ?_
        rw [k_pend b hb]
        rcases List.mem_append.mp ha with ha' | ha'
        · rcases List.mem_append.mp ha' with ha'' | ha''
          · rcases List.mem_append.mp ha'' with h3 | h3
            · rcases List.mem_append.mp h3 with h4 | h4
              · rw [k_bal a h4]; decide
              · rw [k_nonce a h4]; decide
            · rw [k_reg a h3]; decide
          · rw [k_lp a ha'']; decide
        · rw [k_cons a ha']; decide
    · intro a ha b hb
      refine ne_of_kindIndex_ne ?_
      rw [k_eb b hb]
      rcases List.mem_append.mp ha with ha' | ha'
      · rcases List.mem_append.mp ha' with ha'' | ha''
        · rcases List.mem_append.mp ha'' with h3 | h3
          · rcases List.mem_append.mp h3 with h4 | h4
            · rcases List.mem_append.mp h4 with h5 | h5
              · rw [k_bal a h5]; decide
              · rw [k_nonce a h5]; decide
            · rw [k_reg a h4]; decide
          · rw [k_lp a h3]; decide
        · rw [k_cons a ha'']; decide
      · rw [k_pend a ha']; decide
  · intro a ha b hb
    refine ne_of_kindIndex_ne ?_
    obtain ⟨h_ge, h_ne13⟩ := k_single b hb
    rcases List.mem_append.mp ha with ha' | ha'
    · rcases List.mem_append.mp ha' with ha'' | ha''
      · rcases List.mem_append.mp ha'' with h3 | h3
        · rcases List.mem_append.mp h3 with h4 | h4
          · rcases List.mem_append.mp h4 with h5 | h5
            · rcases List.mem_append.mp h5 with h6 | h6
              · rw [k_bal a h6]; omega
              · rw [k_nonce a h6]; omega
            · rw [k_reg a h5]; omega
          · rw [k_lp a h4]; omega
        · rw [k_cons a h3]; omega
      · rw [k_pend a ha'']; omega
    · rw [k_eb a ha']; omega

/-! ## Enumeration completeness for the keyed sub-states

`StateCells` proves the balance and epoch-budget entries are
enumerated.  The remaining five keyed sub-states need the same
statement, because the absent-cell lemma below reads them
contrapositively: a cell that is not enumerated is a cell whose
sub-state has no entry, hence one that reads canonically absent. -/

/-- A live nonce entry is enumerated. -/
theorem nonce_tag_enumerated (es : ExtendedState) (a : ActorId) (n : Nonce)
    (h : es.nonces.next[a]? = some n) : CellTag.nonce a ∈ stateCellTags es := by
  unfold stateCellTags
  simp only [List.mem_append, List.mem_map]
  exact Or.inl (Or.inl (Or.inl (Or.inl (Or.inl (Or.inl (Or.inr
    ⟨(a, n), Std.TreeMap.mem_toList_iff_getElem?_eq_some.mpr h, rfl⟩))))))

/-- A live registry entry is enumerated. -/
theorem registry_tag_enumerated (es : ExtendedState) (a : ActorId) (pk : PublicKey)
    (h : es.registry[a]? = some pk) : CellTag.registry a ∈ stateCellTags es := by
  unfold stateCellTags
  simp only [List.mem_append, List.mem_map]
  exact Or.inl (Or.inl (Or.inl (Or.inl (Or.inl (Or.inr
    ⟨(a, pk), Std.TreeMap.mem_toList_iff_getElem?_eq_some.mpr h, rfl⟩)))))

/-- A live local-policy entry is enumerated. -/
theorem localPolicy_tag_enumerated (es : ExtendedState) (a : ActorId)
    (p : LocalPolicy) (h : es.localPolicies[a]? = some p) :
    CellTag.localPolicy a ∈ stateCellTags es := by
  unfold stateCellTags
  simp only [List.mem_append, List.mem_map]
  exact Or.inl (Or.inl (Or.inl (Or.inl (Or.inr
    ⟨(a, p), Std.TreeMap.mem_toList_iff_getElem?_eq_some.mpr h, rfl⟩))))

/-- A live consumed-deposit entry is enumerated. -/
theorem bridgeConsumed_tag_enumerated (es : ExtendedState) (d : DepositId)
    (dr : DepositRecord) (h : es.bridge.consumed[d]? = some dr) :
    CellTag.bridgeConsumed d ∈ stateCellTags es := by
  unfold stateCellTags
  simp only [List.mem_append, List.mem_map]
  exact Or.inl (Or.inl (Or.inl (Or.inr
    ⟨(d, dr), Std.TreeMap.mem_toList_iff_getElem?_eq_some.mpr h, rfl⟩)))

/-- A live pending-withdrawal entry is enumerated. -/
theorem bridgePending_tag_enumerated (es : ExtendedState) (w : WithdrawalId)
    (pw : PendingWithdrawal) (h : es.bridge.pending[w]? = some pw) :
    CellTag.bridgePending w ∈ stateCellTags es := by
  unfold stateCellTags
  simp only [List.mem_append, List.mem_map]
  exact Or.inl (Or.inl (Or.inr
    ⟨(w, pw), Std.TreeMap.mem_toList_iff_getElem?_eq_some.mpr h, rfl⟩))

/-- A cell the enumeration omits reads as the canonical absent value.

    This is the contract `canonicalAbsentValue` names and the SMT
    root relies on: an absent leaf reads as the canonical empty
    sub-tree, so enumerating absent cells would change the root
    without changing the state.  The singleton tags are enumerated
    unconditionally, so for those the hypothesis is what is
    absurd. -/
theorem getCellValue_of_not_mem (es : ExtendedState) (t : CellTag)
    (h : t ∉ stateCellTags es) : getCellValue es t = canonicalAbsentValue t := by
  cases t with
  | balance r a =>
    have h_zero : LegalKernel.getBalance es.base r a = 0 := by
      unfold LegalKernel.getBalance
      match h_outer : es.base.balances[r]? with
      | none => rfl
      | some bm =>
        match h_inner : bm[a]? with
        | none => show bm[a]?.getD 0 = 0; rw [h_inner]; rfl
        | some v =>
          exact absurd (balance_tag_enumerated es r a bm v
            (Std.TreeMap.mem_toList_iff_getElem?_eq_some.mpr h_outer)
            (Std.TreeMap.mem_toList_iff_getElem?_eq_some.mpr h_inner)) h
    simp only [getCellValue, canonicalAbsentValue, h_zero]
  | nonce a =>
    have h_zero : Authority.expectsNonce es a = 0 := by
      unfold Authority.expectsNonce
      match h_n : es.nonces.next[a]? with
      | none => rfl
      | some n => exact absurd (nonce_tag_enumerated es a n h_n) h
    simp only [getCellValue, canonicalAbsentValue, h_zero]
  | registry a =>
    match h_r : es.registry[a]? with
    | none    => simp only [getCellValue, canonicalAbsentValue, h_r]
    | some pk => exact absurd (registry_tag_enumerated es a pk h_r) h
  | localPolicy a =>
    match h_p : es.localPolicies[a]? with
    | none   => simp only [getCellValue, canonicalAbsentValue, h_p]
    | some p => exact absurd (localPolicy_tag_enumerated es a p h_p) h
  | bridgeConsumed d =>
    match h_d : es.bridge.consumed[d]? with
    | none    =>
      simp only [getCellValue, canonicalAbsentValue,
        Std.TreeMap.contains_eq_isSome_getElem?, h_d, Option.isSome_none,
        Bool.false_eq_true, if_false]
    | some dr => exact absurd (bridgeConsumed_tag_enumerated es d dr h_d) h
  | bridgePending w =>
    match h_w : es.bridge.pending[w]? with
    | none    => simp only [getCellValue, canonicalAbsentValue, h_w]
    | some pw => exact absurd (bridgePending_tag_enumerated es w pw h_w) h
  | epochBudget a =>
    match h_b : es.epochBudgets[a]? with
    | none   => simp only [getCellValue, canonicalAbsentValue, h_b, Option.getD_none]; rfl
    | some b => exact absurd (epochBudget_tag_enumerated es a b
                  (Std.TreeMap.mem_toList_iff_getElem?_eq_some.mpr h_b)) h
  | bridgeNextWdId => exact absurd (singleton_tags_enumerated es _ (by decide)) h
  | bridgeAmmReserveEth => exact absurd (singleton_tags_enumerated es _ (by decide)) h
  | bridgeAmmReserveBold => exact absurd (singleton_tags_enumerated es _ (by decide)) h
  | bridgeBoldCircuitClosed => exact absurd (singleton_tags_enumerated es _ (by decide)) h
  | bridgeBoldTvlCap => exact absurd (singleton_tags_enumerated es _ (by decide)) h
  | bridgeBoldTotalLockedValue =>
    exact absurd (singleton_tags_enumerated es _ (by decide)) h
  | bridgeAmmDisabled => exact absurd (singleton_tags_enumerated es _ (by decide)) h
  | budgetPolicyFreeTier => exact absurd (singleton_tags_enumerated es _ (by decide)) h
  | budgetPolicyActionCost => exact absurd (singleton_tags_enumerated es _ (by decide)) h
  | budgetPolicyCurrentEpoch =>
    exact absurd (singleton_tags_enumerated es _ (by decide)) h

/-! ## Well-formedness and the pre-image set

Two side conditions, both real rather than decorative.  The key
bound is the `2^256` word the cell-key layout gives `DepositId` and
`WithdrawalId` (which are `Nat`, so unbounded in principle); the
value bound is the CBE byte-string length head the leaf encoding
rides. -/

/-- Every enumerated cell of `es` fits the widths the cell root's
    encodings give it. -/
def StateCellsWellFormed (es : ExtendedState) : Prop :=
  ∀ t ∈ stateCellTags es,
    t.KeyBounded ∧ (getCellValue es t).size < 256 ^ 8

/-- The cell-key pre-images the key-injectivity step hashes. -/
def stateCellKeyPreimages (es₁ es₂ : ExtendedState) : List ByteArray :=
  (stateCellTags es₁ ++ stateCellTags es₂).map cellKeyPreimage

/-- Every `hashBytes` pre-image the determination argument consumes:
    the two roots' recursions, the empty-sub-tree chain, and the cell
    keys.  `CollisionFreeOn` is scoped to a finite list, so this is
    the list. -/
def stateCommitSmtPreimages (es₁ es₂ : ExtendedState) : List ByteArray :=
  smtRootPreimages smtDepth (stateCellEntries es₁) ++
    smtRootPreimages smtDepth (stateCellEntries es₂) ++
    emptyRootPreimages smtDepth ++
    stateCellKeyPreimages es₁ es₂

/-- Cell keys are 32 bytes, so they index a depth-256 SMT and fit the
    CBE length head with room to spare. -/
private theorem entries_key_size (es : ExtendedState) :
    ∀ p ∈ stateCellEntries es, p.1.size = 32 := by
  intro p hp
  obtain ⟨t, _, rfl, _⟩ := stateCellEntries_spec es p hp
  exact smtCellKey_size t

/-- Distinct enumerated cells get distinct SMT keys. -/
theorem stateCellEntries_keys_pairwise_ne (es₁ es₂ : ExtendedState)
    (h_wf₁ : StateCellsWellFormed es₁) (h_wf₂ : StateCellsWellFormed es₂)
    (h_cf : CollisionFreeOn (stateCellKeyPreimages es₁ es₂) hashBytes)
    {t₁ t₂ : CellTag}
    (h₁ : t₁ ∈ stateCellTags es₁ ++ stateCellTags es₂)
    (h₂ : t₂ ∈ stateCellTags es₁ ++ stateCellTags es₂)
    (h : smtCellKey t₁ = smtCellKey t₂) : t₁ = t₂ := by
  have bounded : ∀ {t : CellTag},
      t ∈ stateCellTags es₁ ++ stateCellTags es₂ → t.KeyBounded := by
    intro t ht
    rcases List.mem_append.mp ht with ht' | ht'
    · exact (h_wf₁ t ht').1
    · exact (h_wf₂ t ht').1
  refine smtCellKey_injective_under_collision_free t₁ t₂ (h_cf.mono ?_)
    (cellKeyPreimage_injective t₁ t₂ (bounded h₁) (bounded h₂)) h
  intro x hx
  rcases List.mem_cons.mp hx with rfl | hx'
  · exact List.mem_map_of_mem h₁
  · rw [List.mem_singleton.mp hx']
    exact List.mem_map_of_mem h₂

/-- The entry list is `BitsDistinctBelow` at full depth — the
    hypothesis `smtRootListAux_perm_of_eq_under_collision_free`
    consumes, discharged from tag distinctness plus key
    injectivity. -/
theorem stateCellEntries_bitsDistinct (es₁ es₂ : ExtendedState)
    (h_wf₁ : StateCellsWellFormed es₁) (h_wf₂ : StateCellsWellFormed es₂)
    (h_cf : CollisionFreeOn (stateCellKeyPreimages es₁ es₂) hashBytes)
    (es : ExtendedState) (h_es : es = es₁ ∨ es = es₂) :
    BitsDistinctBelow smtDepth (stateCellEntries es) := by
  refine bitsDistinctBelow_of_keys_pairwise_ne (entries_key_size es) ?_
  have h_sub : ∀ t ∈ stateCellTags es, t ∈ stateCellTags es₁ ++ stateCellTags es₂ := by
    intro t ht
    rcases h_es with rfl | rfl
    · exact List.mem_append_left _ ht
    · exact List.mem_append_right _ ht
  -- The entries are the tags' images under a partial map, so
  -- distinctness descends from tag distinctness: two entries come
  -- from two distinct tags, and distinct tags have distinct keys.
  unfold stateCellEntries
  refine List.pairwise_filterMap.mpr
    (List.Pairwise.imp_of_mem ?_ (stateCellTags_nodup es))
  intro a b ha hb h_ne x hx y hy
  -- Read the key off each side's `some`.
  have h_key : ∀ (t : CellTag) (z : ByteArray × ByteArray),
      (if getCellValue es t = canonicalAbsentValue t then none
       else some (smtCellKey t, getCellValue es t)) = some z → z.1 = smtCellKey t := by
    intro t z hz
    by_cases h_abs : getCellValue es t = canonicalAbsentValue t
    · rw [if_pos h_abs] at hz; exact absurd hz (by simp)
    · rw [if_neg h_abs] at hz; rw [← Option.some.inj hz]
  rw [h_key a x hx, h_key b y hy]
  intro h_eq
  exact h_ne (stateCellEntries_keys_pairwise_ne es₁ es₂ h_wf₁ h_wf₂ h_cf
    (h_sub a ha) (h_sub b hb) h_eq)

/-- Both components of every entry fit the CBE byte-string head. -/
theorem stateCellEntries_encodable (es : ExtendedState)
    (h_wf : StateCellsWellFormed es) : EntriesEncodable (stateCellEntries es) := by
  intro p hp
  obtain ⟨t, ht, rfl, _⟩ := stateCellEntries_spec es p hp
  exact ⟨by rw [smtCellKey_size t]; decide, (h_wf t ht).2⟩

/-! ## The determination theorem -/

/-- Equal SMT state roots imply the two states' cell entries are
    permutations of one another.  The composition of
    `smtRootListAux_perm_of_eq_under_collision_free` with the
    enumeration's well-formedness. -/
theorem stateCellEntries_perm_of_commitSmt_eq (es₁ es₂ : ExtendedState)
    (h_wf₁ : StateCellsWellFormed es₁) (h_wf₂ : StateCellsWellFormed es₂)
    (h_cf : CollisionFreeOn (stateCommitSmtPreimages es₁ es₂) hashBytes)
    (h : commitExtendedState es₁ = commitExtendedState es₂) :
    (stateCellEntries es₁).Perm (stateCellEntries es₂) := by
  have h_cf_key : CollisionFreeOn (stateCellKeyPreimages es₁ es₂) hashBytes :=
    h_cf.append_right
  exact smtRootListAux_perm_of_eq_under_collision_free smtDepth (by unfold smtDepth; omega)
    _ _
    (stateCellEntries_bitsDistinct es₁ es₂ h_wf₁ h_wf₂ h_cf_key es₁ (Or.inl rfl))
    (stateCellEntries_bitsDistinct es₁ es₂ h_wf₁ h_wf₂ h_cf_key es₂ (Or.inr rfl))
    (stateCellEntries_encodable es₁ h_wf₁) (stateCellEntries_encodable es₂ h_wf₂)
    h_cf.append_left h

/-- One direction of the transfer: a cell of `es₁` that carries a
    non-absent value reads the same in `es₂`.

    The hypothesis is non-absence rather than mere enumeration
    because the entry list drops canonically-absent cells: those are
    not in the tree at all, and the "reads the same" conclusion for
    them comes from both sides reading canonically absent. -/
private theorem cell_transfer (es₁ es₂ : ExtendedState)
    (h_wf₁ : StateCellsWellFormed es₁) (h_wf₂ : StateCellsWellFormed es₂)
    (h_cf : CollisionFreeOn (stateCellKeyPreimages es₁ es₂) hashBytes)
    (h_perm : (stateCellEntries es₁).Perm (stateCellEntries es₂))
    (t : CellTag) (ht : t ∈ stateCellTags es₁)
    (h_ne : getCellValue es₁ t ≠ canonicalAbsentValue t) :
    getCellValue es₁ t = getCellValue es₂ t := by
  have h_mem : (smtCellKey t, getCellValue es₁ t) ∈ stateCellEntries es₂ :=
    h_perm.mem_iff.mp (mem_stateCellEntries_of_ne_absent es₁ t ht h_ne)
  obtain ⟨t', ht', h_pair, _⟩ := stateCellEntries_spec es₂ _ h_mem
  have h_key : smtCellKey t = smtCellKey t' := congrArg Prod.fst h_pair
  have h_val : getCellValue es₁ t = getCellValue es₂ t' := congrArg Prod.snd h_pair
  have h_eq : t = t' :=
    stateCellEntries_keys_pairwise_ne es₁ es₂ h_wf₁ h_wf₂ h_cf
      (List.mem_append_left _ ht) (List.mem_append_right _ ht') h_key
  rw [h_eq] at h_val ⊢
  exact h_val

/-- **The SMT state root determines every cell.**

    Two states behind the same published root read identically
    through the cell interface — which is the whole interface the L1
    step VM has, so it is exactly what the fault-proof game needs.

    This replaces
    `commitExtendedState_subcommits_extensional_eq_under_collision_free`
    (EI.8) for the cell root.  The conclusion is behavioural rather
    than `ExtendedState.extEq` because `extEq` is not reachable and
    should not be: `State.Equiv` separates a resource present with an
    all-zero balance map from a resource absent entirely, and no cell
    read — hence no step — can tell those apart. -/
theorem commitExtendedState_determines_cells (es₁ es₂ : ExtendedState)
    (h_wf₁ : StateCellsWellFormed es₁) (h_wf₂ : StateCellsWellFormed es₂)
    (h_cf : CollisionFreeOn (stateCommitSmtPreimages es₁ es₂) hashBytes)
    (h : commitExtendedState es₁ = commitExtendedState es₂) :
    ∀ t : CellTag, getCellValue es₁ t = getCellValue es₂ t := by
  have h_cf_key : CollisionFreeOn (stateCellKeyPreimages es₁ es₂) hashBytes :=
    h_cf.append_right
  have h_perm := stateCellEntries_perm_of_commitSmt_eq es₁ es₂ h_wf₁ h_wf₂ h_cf h
  -- The mirrored key-pre-image set, for the reverse transfer.
  have h_cf_key' : CollisionFreeOn (stateCellKeyPreimages es₂ es₁) hashBytes := by
    refine h_cf_key.mono ?_
    intro x hx
    obtain ⟨t, ht, rfl⟩ := List.mem_map.mp hx
    refine List.mem_map_of_mem ?_
    rcases List.mem_append.mp ht with ht' | ht'
    · exact List.mem_append_right _ ht'
    · exact List.mem_append_left _ ht'
  intro t
  -- Three cases, keyed on non-absence rather than on enumeration:
  -- a canonically-absent cell contributes no entry, so the entry
  -- permutation says nothing about it — and nothing needs to be
  -- said, since both sides then read the same canonical value.
  by_cases h₁ : getCellValue es₁ t = canonicalAbsentValue t
  · by_cases h₂ : getCellValue es₂ t = canonicalAbsentValue t
    · rw [h₁, h₂]
    · -- Absent on the left, present on the right: impossible, since
      -- the reverse transfer carries the right's value to the left.
      have h_mem₂ : t ∈ stateCellTags es₂ :=
        Classical.byContradiction fun h_c => h₂ (getCellValue_of_not_mem es₂ t h_c)
      exact absurd
        ((cell_transfer es₂ es₁ h_wf₂ h_wf₁ h_cf_key' h_perm.symm t h_mem₂ h₂).trans h₁)
        h₂
  · have h_mem₁ : t ∈ stateCellTags es₁ :=
      Classical.byContradiction fun h_c => h₁ (getCellValue_of_not_mem es₁ t h_c)
    exact cell_transfer es₁ es₂ h_wf₁ h_wf₂ h_cf_key h_perm t h_mem₁ h₁

/-! ## Opening a cell against the published root

The step VM reads cells it does not hold the state for, so it needs
a verifier that works against `commitExtendedState` alone.  The
subtlety is absence: a cell with no entry has an EMPTY sub-tree
beneath its key, not a leaf holding the canonical absent value, so
its opening walks from a different starting leaf.  A verifier
holding only the claimed value can tell which because
`stateCellEntries` drops canonically-absent cells — that filter is
what makes "value is canonically absent" and "key is absent from the
tree" the same condition.

Crediting a receiver who holds no balance yet is the common case,
so this is not an edge case the step VM can decline to handle. -/

/-- The leaf a cell occupies in the state root: its leaf hash when
    present, the canonical empty leaf when canonically absent. -/
def cellLeaf (t : CellTag) (value : ByteArray) : ByteArray :=
  if value = canonicalAbsentValue t then emptyRootAt 0
  else leafHash (smtCellKey t) value

/-- Verify a cell opening against a published state root. -/
def verifyStateCellProof (root : StateCommit) (t : CellTag)
    (value : ByteArray) (proof : SmtCellProof) : Bool :=
  proof.isWellFormed && decide (smtWalkFrom (cellLeaf t value) (smtCellKey t) proof = root)

/-- The canonical opening for a cell of `es`: the sibling path along
    its key. -/
def buildStateCellProof (es : ExtendedState) (t : CellTag) : SmtCellProof :=
  let (sibs, bitDepths) :=
    buildSmtCellProofAux smtDepth (stateCellEntries es) (smtCellKey t)
  { siblings := sibs.toArray
  , bitmask  := bitDepths.foldl setBitmaskBit
                  (ByteArray.mk (Array.replicate 32 (0 : UInt8))) }

/-- **Completeness for a present cell.**  The canonical sibling path
    walks a live cell's leaf back to the published root. -/
theorem canonicalSiblings_verifies_present (es : ExtendedState) (t : CellTag)
    (h_mem : t ∈ stateCellTags es)
    (h_ne : getCellValue es t ≠ canonicalAbsentValue t)
    (h_wf : BitsDistinctBelow smtDepth (stateCellEntries es)) :
    ((canonicalSiblings smtDepth (stateCellEntries es) (smtCellKey t)).zip
        (keyBits (smtCellKey t))).foldl stepPair (cellLeaf t (getCellValue es t))
      = commitExtendedState es := by
  unfold cellLeaf
  rw [if_neg h_ne]
  exact canonicalSiblings_walks_to_root smtDepth (stateCellEntries es)
    (smtCellKey t) (getCellValue es t)
    (mem_stateCellEntries_of_ne_absent es t h_mem h_ne) h_wf

/-- **Completeness for an absent cell.**  A cell the state does not
    hold walks from the canonical empty leaf back to the same root —
    the case a step hits whenever it credits a fresh actor.

    The key-injectivity hypothesis is what rules out some OTHER
    cell's entry sitting at this cell's key. -/
theorem canonicalSiblings_verifies_absent (es : ExtendedState) (t : CellTag)
    (h_abs : getCellValue es t = canonicalAbsentValue t)
    (h_keys : ∀ t' ∈ stateCellTags es, smtCellKey t' ≠ smtCellKey t) :
    ((canonicalSiblings smtDepth (stateCellEntries es) (smtCellKey t)).zip
        (keyBits (smtCellKey t))).foldl stepPair (cellLeaf t (getCellValue es t))
      = commitExtendedState es := by
  unfold cellLeaf
  rw [if_pos h_abs]
  refine canonicalSiblings_walks_to_root_absent (stateCellEntries es) (smtCellKey t)
    (entries_key_size es) (smtCellKey_size t) ?_
  intro p hp
  obtain ⟨t', ht', rfl, _⟩ := stateCellEntries_spec es p hp
  exact h_keys t' ht'

/-! ## Writing a cell into the published root

The step VM holds a root and a bundle of openings, not a state, so
the post-root has to be computable from those alone.  It is: the
pre-state supplies the sibling path, the write supplies the leaf, and
`smtRootListAux_update_single` says the two compose to the post-state's
own published root — provided the two states really do agree at every
other cell, which is `dropKey`-equality of their entry lists.

Both directions of the absence branch appear here, because a step
writes canonically-absent values routinely: `reclaimAmmReserves`
sweeps a balance to zero and `revokeLocalPolicy` clears a policy. -/

/-- A cell's leaf is 32 bytes either way, so it composes with the
    next write in a multi-cell step. -/
theorem cellLeaf_size (t : CellTag) (value : ByteArray) :
    (cellLeaf t value).size = 32 := by
  unfold cellLeaf
  by_cases h : value = canonicalAbsentValue t
  · rw [if_pos h]; exact emptyRootAt_size 0
  · rw [if_neg h]; exact leafHash_size _ _

/-- The root after writing `newValue` into the cell the opening
    covers.  This is the L1 step VM's per-write primitive: same walk,
    new leaf. -/
def updateStateCellRoot (t : CellTag) (newValue : ByteArray)
    (proof : SmtCellProof) : StateCommit :=
  smtWalkFrom (cellLeaf t newValue) (smtCellKey t) proof

/-- **The write lands on the post-state's own root.**  Walking the
    PRE-state's canonical path for a cell, started from that cell's
    POST leaf, reaches exactly `commitExtendedState es'`.

    The `dropKey` hypothesis is the substantive one: it says the two
    states' entry lists agree away from this cell, which is what
    licenses reusing the pre-state's path. -/
theorem canonicalSiblings_updates_root
    (es es' : ExtendedState) (t : CellTag)
    (h_off : dropKey (stateCellEntries es) (smtCellKey t)
           = dropKey (stateCellEntries es') (smtCellKey t))
    (h_wf' : BitsDistinctBelow smtDepth (stateCellEntries es'))
    (h_keys' : getCellValue es' t = canonicalAbsentValue t →
                 ∀ t' ∈ stateCellTags es', smtCellKey t' ≠ smtCellKey t)
    (h_mem' : getCellValue es' t ≠ canonicalAbsentValue t → t ∈ stateCellTags es') :
    ((canonicalSiblings smtDepth (stateCellEntries es) (smtCellKey t)).zip
        (keyBits (smtCellKey t))).foldl stepPair (cellLeaf t (getCellValue es' t))
      = commitExtendedState es' := by
  unfold cellLeaf
  by_cases h_abs : getCellValue es' t = canonicalAbsentValue t
  · rw [if_pos h_abs]
    refine smtRootListAux_update_to_absent _ _ _ h_off (entries_key_size es')
      (smtCellKey_size t) (fun p hp => ?_)
    obtain ⟨t', ht', rfl, _⟩ := stateCellEntries_spec es' p hp
    exact h_keys' h_abs t' ht'
  · rw [if_neg h_abs]
    exact smtRootListAux_update_to_present _ _ _ _ h_off h_wf'
      (mem_stateCellEntries_of_ne_absent es' t (h_mem' h_abs) h_abs)

/-- The step-VM-facing form: an opening whose expansion is the
    pre-state's canonical path computes the post-state's published
    root when re-walked from the post leaf.

    The representation obligation stays where §2C left it — that
    `buildStateCellProof`'s bitmask encoding expands to the canonical
    path is pinned by `faultproof-smt-injective` rather than proved —
    so it is taken as the hypothesis `h_expand` rather than assumed
    silently. -/
theorem updateStateCellRoot_eq_commit_of_canonical
    (es es' : ExtendedState) (t : CellTag) (canon : SmtCellProof)
    (h_expand : expandSiblings canon
        = canonicalSiblings smtDepth (stateCellEntries es) (smtCellKey t))
    (h_off : dropKey (stateCellEntries es) (smtCellKey t)
           = dropKey (stateCellEntries es') (smtCellKey t))
    (h_wf' : BitsDistinctBelow smtDepth (stateCellEntries es'))
    (h_keys' : getCellValue es' t = canonicalAbsentValue t →
                 ∀ t' ∈ stateCellTags es', smtCellKey t' ≠ smtCellKey t)
    (h_mem' : getCellValue es' t ≠ canonicalAbsentValue t → t ∈ stateCellTags es') :
    updateStateCellRoot t (getCellValue es' t) canon = commitExtendedState es' := by
  unfold updateStateCellRoot smtWalkFrom
  rw [h_expand]
  exact canonicalSiblings_updates_root es es' t h_off h_wf' h_keys' h_mem'

/-- **A responder cannot steer the post-root.**  Two openings that
    both verify the same cell against the same published root compute
    the same post-root for the same written value — so the value the
    L1 folds is a function of `(pre-root, cell, new value)` alone.

    This is `smtUpdateRoot_proof_independent` lifted through the
    absence branch: the present case verifies from a leaf hash and the
    absent case from the canonical empty leaf, so the guarantee has to
    be stated over the starting leaf. -/
theorem updateStateCellRoot_proof_independent
    (es : ExtendedState) (t : CellTag) (newValue : ByteArray)
    (proof₁ proof₂ : SmtCellProof)
    (h_cf : Bridge.CollisionFreeOn
      (smtWalkPairPreimages (cellLeaf t (getCellValue es t)) (smtCellKey t)
        proof₁ proof₂) LegalKernel.Runtime.hashBytes)
    (h₁ : verifyStateCellProof (commitExtendedState es) t (getCellValue es t) proof₁ = true)
    (h₂ : verifyStateCellProof (commitExtendedState es) t (getCellValue es t) proof₂ = true) :
    updateStateCellRoot t newValue proof₁ = updateStateCellRoot t newValue proof₂ := by
  unfold verifyStateCellProof at h₁ h₂
  rw [Bool.and_eq_true] at h₁ h₂
  obtain ⟨h_wf₁, h_walk₁⟩ := h₁
  obtain ⟨h_wf₂, h_walk₂⟩ := h₂
  exact smtWalkFrom_proof_independent (commitExtendedState es) (smtCellKey t)
    (cellLeaf t (getCellValue es t)) (cellLeaf t newValue) proof₁ proof₂
    h_cf (cellLeaf_size t _) h_wf₁ h_wf₂
    (decide_eq_true_eq.mp h_walk₁) (decide_eq_true_eq.mp h_walk₂)

/-! ## Folding a step's writes

A step writes several cells, and openings go stale the moment a write
lands: the sibling roots along one cell's path move when a different
cell under a shared ancestor is rewritten.  So the bundle is folded
strictly in order, each opening checked against the root the previous
write produced.  A duplicate entry for an already-written cell fails
that check, which is the fail-closed direction. -/

/-- One checked write: verify the opening against the CURRENT root,
    then re-walk it from the new leaf. -/
def applyStateCellWrite (root : StateCommit) (t : CellTag)
    (oldValue newValue : ByteArray) (proof : SmtCellProof) : Option StateCommit :=
  if verifyStateCellProof root t oldValue proof then
    some (updateStateCellRoot t newValue proof)
  else none

/-- One entry of a step's write bundle: cell, proven pre-value, new
    value, opening. -/
abbrev StateCellWrite := CellTag × ByteArray × ByteArray × SmtCellProof

/-- Fold a step's writes into the root, in order. -/
def foldStateCellWrites (root : StateCommit) : List StateCellWrite → Option StateCommit
  | [] => some root
  | (t, oldV, newV, p) :: rest =>
    match applyStateCellWrite root t oldV newV p with
    | none    => none
    | some r' => foldStateCellWrites r' rest

/-- A step's writes, each paired with the state it produces and the
    opening it used. -/
abbrev CellWriteChain := List (ExtendedState × CellTag × SmtCellProof)

/-- The write bundle a chain induces: each entry's pre-value is read
    from the state it opens against and its new value from the state
    it produces. -/
def chainWrites (es : ExtendedState) : CellWriteChain → List StateCellWrite
  | [] => []
  | (es', t, p) :: rest =>
      (t, getCellValue es t, getCellValue es' t, p) :: chainWrites es' rest

/-- The state a chain ends in. -/
def chainLast (es : ExtendedState) : CellWriteChain → ExtendedState
  | [] => es
  | (es', _, _) :: rest => chainLast es' rest

/-- Every link is a well-formed single-cell write: the opening is the
    canonical path of the state it opens against and verifies there,
    and the successor state agrees with its predecessor away from the
    written cell. -/
def ChainCoherent (es : ExtendedState) : CellWriteChain → Prop
  | [] => True
  | (es', t, p) :: rest =>
      expandSiblings p = canonicalSiblings smtDepth (stateCellEntries es) (smtCellKey t)
      ∧ dropKey (stateCellEntries es) (smtCellKey t)
          = dropKey (stateCellEntries es') (smtCellKey t)
      ∧ BitsDistinctBelow smtDepth (stateCellEntries es')
      ∧ (getCellValue es' t = canonicalAbsentValue t →
           ∀ t' ∈ stateCellTags es', smtCellKey t' ≠ smtCellKey t)
      ∧ (getCellValue es' t ≠ canonicalAbsentValue t → t ∈ stateCellTags es')
      ∧ verifyStateCellProof (commitExtendedState es) t (getCellValue es t) p = true
      ∧ ChainCoherent es' rest

/-- **The step VM's fold lands on the post-state's published root.**
    Given a coherent chain of single-cell writes, folding the bundle
    into the pre-state's root computes exactly
    `commitExtendedState` of the state the chain ends in.

    This is what closes the loop the plan's §4 opens: the L1 holds a
    root and openings rather than a state, and this says the number it
    folds out of them is the root an honest sequencer publishes. -/
theorem foldStateCellWrites_eq_commit_of_coherent :
    ∀ (chain : CellWriteChain) (es : ExtendedState), ChainCoherent es chain →
      foldStateCellWrites (commitExtendedState es) (chainWrites es chain)
        = some (commitExtendedState (chainLast es chain)) := by
  intro chain
  induction chain with
  | nil => intro _ _; rfl
  | cons hd rest ih =>
    obtain ⟨es', t, p⟩ := hd
    intro es hc
    obtain ⟨h_exp, h_off, h_wf', h_keys', h_mem', h_ver, h_rest⟩ := hc
    show (match applyStateCellWrite (commitExtendedState es) t (getCellValue es t)
                  (getCellValue es' t) p with
          | none    => none
          | some r' => foldStateCellWrites r' (chainWrites es' rest))
        = some (commitExtendedState (chainLast es' rest))
    rw [show applyStateCellWrite (commitExtendedState es) t (getCellValue es t)
              (getCellValue es' t) p = some (commitExtendedState es') from by
          unfold applyStateCellWrite
          rw [if_pos h_ver,
            updateStateCellRoot_eq_commit_of_canonical es es' t p h_exp h_off h_wf'
              h_keys' h_mem']]
    exact ih es' h_rest

end FaultProof
end LegalKernel
