// SPDX-License-Identifier: GPL-3.0-or-later
// Knomosis  - A Societal Kernel
// Copyright (C) 2026  Adam Hall
// This program comes with ABSOLUTELY NO WARRANTY.
// This is free software, and you are welcome to redistribute it
// under certain conditions. See: https://github.com/hatter6822/Knomosis/blob/main/LICENSE

//! Cross-stack fixture loader for the Knomosis Rust host workspace.
//!
//! ## What this crate provides
//!
//! Every Knomosis Rust crate with a cross-stack contract (RH-A.1
//! ECDSA, RH-A.2 keccak256, RH-B ingest, RH-C host, RH-G observer)
//! has a Lean reference whose byte-output it must reproduce
//! byte-for-byte.  The reference is published as a *fixture file* —
//! a sequence of `(input, expected)` byte-pairs generated by Lean
//! and shipped under `runtime/tests/cross-stack/`.  Consumer crates
//! dev-dep on `knomosis-cross-stack` and call [`FixtureFile::load`] to
//! enumerate the records.
//!
//! ## File format
//!
//! The on-disk format is a small, self-describing framing layer over
//! opaque byte payloads.  The payloads themselves are usually
//! CBE-encoded (the project's canonical binary encoding from
//! `LegalKernel/Encoding/`), but this crate does **not** decode CBE
//! — it treats both `input` and `expected` as opaque
//! [`Vec<u8>`].  Consumers compare byte-equality against their own
//! Rust implementation's output.  Treating the inner bytes as opaque
//! is deliberate:
//!
//!   * Rust does not have a CBE decoder yet; building one inside RH-H
//!     would prefigure design decisions that belong to the downstream
//!     work units.
//!   * Byte-equality is the load-bearing cross-stack contract.  Any
//!     parsing inside this crate would weaken the contract by
//!     reasoning over a structured form rather than the bytes
//!     themselves.
//!
//! Concretely, the file layout is:
//!
//! ```text
//! offset  size   field
//! ------  -----  --------------------------------------------------
//!     0     4   magic: ASCII "CXSF" = 0x43 0x58 0x53 0x46
//!     4     4   format version (big-endian u32, currently 1)
//!     8     4   fixture kind tag (big-endian u32; see `FixtureKind`)
//!    12     4   record count (big-endian u32)
//!    16     ?   records (one after the other, in order)
//!
//! each record:
//!     0     4   input length (big-endian u32, ≤ MAX_RECORD_BYTES)
//!     4     ?   input bytes
//!     ?     4   expected length (big-endian u32, ≤ MAX_RECORD_BYTES)
//!     ?     ?   expected bytes
//! ```
//!
//! The maximum record length ([`MAX_RECORD_BYTES`]) is 16 MiB; the
//! maximum file size is bounded by the host's memory.  Both bounds
//! exist to defend against a malformed file claiming a length larger
//! than the actual file's remaining bytes (a classic
//! parser-confusion attack class).
//!
//! ## Bit-exact reproducibility
//!
//! Writing the same sequence of records always produces the same
//! bytes — the [`FixtureFile::to_bytes`] / [`FixtureFile::write_to`]
//! pair is deterministic.  This means fixture files round-trip
//! through Lean → Rust → Lean (or any other tool that respects the
//! format) without drift.

#![doc(html_root_url = "https://docs.rs/knomosis-cross-stack/0.1.0")]

use std::fs::File;
use std::io::{BufReader, BufWriter, Read, Write};
use std::path::{Path, PathBuf};

/// Magic bytes at the start of every fixture file: ASCII "CXSF"
/// (Knomosis Cross-Stack Fixtures).
pub const MAGIC: &[u8; 4] = b"CXSF";

/// Current fixture-file format version.  Bumping this is a
/// workspace-level PR per the engineering plan §7 risk register.
pub const FORMAT_VERSION: u32 = 1;

/// Maximum byte-length of any single `input` or `expected` field.
///
/// 16 MiB is more than enough for any realistic cross-stack test
/// vector: ECDSA records are ≤ 256 bytes, keccak inputs are
/// rarely > 1 MiB in practice, and full-state Action corpora
/// fit comfortably inside the limit.  The bound prevents a
/// malformed file from causing a length-driven allocation panic.
pub const MAX_RECORD_BYTES: usize = 16 * 1024 * 1024;

/// Fixture-kind discriminant.
///
/// Each on-disk fixture file is tagged with one of these kinds so
/// the loader can refuse to mix incompatible records (e.g.
/// dev-dep'ing on this crate from RH-A.1's tests and accidentally
/// loading the keccak256 corpus produces a typed error rather than
/// a silent mismatch).
#[derive(Clone, Copy, Debug, Eq, PartialEq, Hash)]
pub enum FixtureKind {
    /// `(input bytes, expected hash bytes)` — used by RH-A.2.
    Hash,
    /// `(serialised (pk, msg, sig) tuple, expected 1-byte
    /// verification verdict)` — used by RH-A.1.
    Ecdsa,
    /// `(CBE-encoded SignedAction, CBE-encoded Verdict)` — used by
    /// RH-C / RH-B.
    SignedAction,
    /// `(CBE-encoded L1 log, CBE-encoded ingested Action)` — used
    /// by RH-B.
    L1Ingest,
    /// `(CBE-encoded GameState + response, CBE-encoded honest
    /// reply)` — used by RH-G.
    FaultProofObserver,
    /// `(L1 fee-split inputs, CBE-encoded depositWithFee Action)`
    /// — used by RH-B (GP.6.1) to pin the encoder's byte-equivalence
    /// with Lean for the Workstream-GP `depositWithFee` action.
    /// Input layout is defined in
    /// `runtime/knomosis-l1-ingest/src/fixture.rs`; see the
    /// [`FeeSplitInput`] documentation there.
    L1IngestFeeSplit,
    /// `(58-byte L1 fee-split input, expected CBE depositWithFee
    /// Action (72 B) ++ recipient post-deposit ``ActorBudget`` CBE
    /// (18 B))` — used by RH-B (GP.6.5) for the `BOLD`-leg tri-stack
    /// budget-mutation corpus.  Extends [`FixtureKind::L1IngestFeeSplit`]
    /// (which carries only the 72-byte Action) by appending the
    /// recipient's post-deposit ``ActorBudget`` CBE, so the corpus pins
    /// the budget-grant dimension too.  The input layout is the same
    /// 58-byte [`FeeSplitInput`] as the fee-split corpus.
    L1IngestBold,
    /// Out-of-band custom kind, identified by its on-disk u32 tag.
    /// Allows downstream work units to introduce new fixture types
    /// without amending this crate's enum.
    Custom(u32),
}

impl FixtureKind {
    /// Decode from the on-disk u32 tag.
    ///
    /// Tags 1..=7 are the named kinds; any other value decodes to
    /// [`FixtureKind::Custom`].  Forward-compatibility: a
    /// future-defined kind in a Lean-side fixture generator does
    /// not break this loader; consumers that care about strictly
    /// typed kinds match on `Custom(_)` and refuse.
    #[must_use]
    pub const fn from_tag(tag: u32) -> Self {
        match tag {
            1 => Self::Hash,
            2 => Self::Ecdsa,
            3 => Self::SignedAction,
            4 => Self::L1Ingest,
            5 => Self::FaultProofObserver,
            6 => Self::L1IngestFeeSplit,
            7 => Self::L1IngestBold,
            other => Self::Custom(other),
        }
    }

    /// Encode to the on-disk u32 tag.
    #[must_use]
    pub const fn to_tag(self) -> u32 {
        match self {
            Self::Hash => 1,
            Self::Ecdsa => 2,
            Self::SignedAction => 3,
            Self::L1Ingest => 4,
            Self::FaultProofObserver => 5,
            Self::L1IngestFeeSplit => 6,
            Self::L1IngestBold => 7,
            Self::Custom(t) => t,
        }
    }
}

/// A single fixture record: input bytes and the expected output
/// bytes the Rust implementation must produce.
#[derive(Clone, Debug, Eq, PartialEq, Hash)]
pub struct FixtureRecord {
    /// Input bytes for the cross-stack call.
    pub input: Vec<u8>,
    /// Expected output bytes; consumers byte-compare their Rust
    /// implementation's output against this.
    pub expected: Vec<u8>,
}

impl FixtureRecord {
    /// Construct a record from owned byte vectors.
    #[must_use]
    pub fn new(input: Vec<u8>, expected: Vec<u8>) -> Self {
        Self { input, expected }
    }
}

/// A loaded fixture file.
///
/// Created by [`FixtureFile::load`] / [`FixtureFile::from_bytes`].
/// Construct from scratch (for tests) via
/// [`FixtureFile::new`].
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct FixtureFile {
    kind: FixtureKind,
    records: Vec<FixtureRecord>,
}

impl FixtureFile {
    /// Construct a new, empty fixture file with the given kind.
    #[must_use]
    pub fn new(kind: FixtureKind) -> Self {
        Self {
            kind,
            records: Vec::new(),
        }
    }

    /// Construct a fixture file from a list of records.
    #[must_use]
    pub fn from_records(kind: FixtureKind, records: Vec<FixtureRecord>) -> Self {
        Self { kind, records }
    }

    /// Fixture kind discriminant.
    #[must_use]
    pub const fn kind(&self) -> FixtureKind {
        self.kind
    }

    /// Records in source order.
    #[must_use]
    pub fn records(&self) -> &[FixtureRecord] {
        &self.records
    }

    /// Append a record.  Used by fixture-builder test helpers.
    pub fn push(&mut self, record: FixtureRecord) {
        self.records.push(record);
    }

    /// Load a fixture file from a filesystem path.
    pub fn load(path: impl AsRef<Path>) -> Result<Self, LoaderError> {
        let path_ref = path.as_ref();
        let f = File::open(path_ref).map_err(|e| LoaderError::Io {
            path: path_ref.to_path_buf(),
            source: e,
        })?;
        let mut reader = BufReader::new(f);
        let mut bytes = Vec::new();
        reader
            .read_to_end(&mut bytes)
            .map_err(|e| LoaderError::Io {
                path: path_ref.to_path_buf(),
                source: e,
            })?;
        Self::from_bytes(&bytes)
    }

    /// Parse a fixture file from a byte buffer.
    pub fn from_bytes(bytes: &[u8]) -> Result<Self, LoaderError> {
        // Header must be present in full before any field-level
        // parse can succeed.  Reject under-length input up front.
        if bytes.len() < 16 {
            return Err(LoaderError::TruncatedHeader {
                actual: bytes.len(),
            });
        }
        // Header fields are at fixed offsets 0/4/8/12.  Every read
        // is bounds-checked by the `bytes.len() < 16` guard above,
        // so the `ok_or` arms are reachable only on a buggy callee
        // (defence in depth).
        if &bytes[0..4] != MAGIC {
            return Err(LoaderError::BadMagic {
                seen: [bytes[0], bytes[1], bytes[2], bytes[3]],
            });
        }
        let (version, _) = read_u32_be_at(bytes, 4).ok_or(LoaderError::TruncatedHeader {
            actual: bytes.len(),
        })?;
        if version != FORMAT_VERSION {
            return Err(LoaderError::UnsupportedVersion { version });
        }
        let (kind_tag, _) = read_u32_be_at(bytes, 8).ok_or(LoaderError::TruncatedHeader {
            actual: bytes.len(),
        })?;
        let kind = FixtureKind::from_tag(kind_tag);
        let (count, _) = read_u32_be_at(bytes, 12).ok_or(LoaderError::TruncatedHeader {
            actual: bytes.len(),
        })?;
        // Defence in depth: a u32-large count combined with the
        // 16-byte header could overflow `usize` arithmetic below
        // on 32-bit hosts.  Bound the count by a sane multiple of
        // the file size before allocating.
        let count_usize =
            usize::try_from(count).map_err(|_| LoaderError::RecordCountTooLarge { count })?;

        let mut records = Vec::with_capacity(count_usize.min(1024));
        let mut cursor = 16;
        for record_index in 0..count_usize {
            let (record, advanced) = read_record(bytes, cursor, record_index)?;
            cursor = advanced;
            records.push(record);
        }
        if cursor != bytes.len() {
            return Err(LoaderError::TrailingBytes {
                trailing: bytes.len() - cursor,
            });
        }
        Ok(Self { kind, records })
    }

    /// Serialise to an in-memory byte buffer.  Inverse of
    /// [`FixtureFile::from_bytes`].
    ///
    /// # Panics
    ///
    /// Panics if `self.records.len()` exceeds [`u32::MAX`], or if
    /// any individual record's `input` / `expected` exceeds
    /// [`u32::MAX`] bytes.  Both bounds are inherent to the on-disk
    /// format (which uses 32-bit length prefixes); callers
    /// constructing fixtures programmatically should respect them.
    /// Constructing such a fixture requires > 18 EB of memory on a
    /// 64-bit host so the bound is practically unreachable.
    #[must_use]
    pub fn to_bytes(&self) -> Vec<u8> {
        // Total size = 16-byte header + Σ (4 + input.len() + 4 +
        // expected.len()) over records.  Use a saturating fold so
        // a theoretical overflow on a pathologically-large fixture
        // returns `usize::MAX` (clamped) instead of panicking in
        // debug builds; the actual allocation below would fail
        // gracefully on OOM.
        let total_size = self.records.iter().fold(16usize, |acc, r| {
            acc.saturating_add(4)
                .saturating_add(r.input.len())
                .saturating_add(4)
                .saturating_add(r.expected.len())
        });
        let mut out = Vec::with_capacity(total_size);
        out.extend_from_slice(MAGIC);
        out.extend_from_slice(&FORMAT_VERSION.to_be_bytes());
        out.extend_from_slice(&self.kind.to_tag().to_be_bytes());
        let count_u32: u32 = u32::try_from(self.records.len())
            .expect("fixture record count fits in u32 (each FixtureFile API enforces this)");
        out.extend_from_slice(&count_u32.to_be_bytes());
        for record in &self.records {
            let in_len = u32::try_from(record.input.len())
                .expect("input record length ≤ u32::MAX (caller-side invariant)");
            out.extend_from_slice(&in_len.to_be_bytes());
            out.extend_from_slice(&record.input);
            let exp_len = u32::try_from(record.expected.len())
                .expect("expected record length ≤ u32::MAX (caller-side invariant)");
            out.extend_from_slice(&exp_len.to_be_bytes());
            out.extend_from_slice(&record.expected);
        }
        out
    }

    /// Write the serialised fixture to `path`, creating or
    /// truncating any existing file at that location.
    pub fn write_to(&self, path: impl AsRef<Path>) -> Result<(), LoaderError> {
        let path_ref = path.as_ref();
        let f = File::create(path_ref).map_err(|e| LoaderError::Io {
            path: path_ref.to_path_buf(),
            source: e,
        })?;
        let mut writer = BufWriter::new(f);
        writer
            .write_all(&self.to_bytes())
            .map_err(|e| LoaderError::Io {
                path: path_ref.to_path_buf(),
                source: e,
            })?;
        writer.flush().map_err(|e| LoaderError::Io {
            path: path_ref.to_path_buf(),
            source: e,
        })?;
        Ok(())
    }
}

/// Read a 4-byte big-endian u32 starting at `offset`.
///
/// On success returns the parsed value together with the next
/// cursor position (`offset + 4`); returns `None` on insufficient
/// bytes or `usize` overflow of the cursor advancement.
///
/// Returning the post-read offset eliminates redundant `checked_add`s
/// at the call sites and removes a latent panic compared to an
/// earlier panic-on-precondition form.
fn read_u32_be_at(bytes: &[u8], offset: usize) -> Option<(u32, usize)> {
    let next = offset.checked_add(4)?;
    let arr: [u8; 4] = bytes.get(offset..next)?.try_into().ok()?;
    Some((u32::from_be_bytes(arr), next))
}

/// Read a single fixture record starting at `cursor`.  Returns the
/// record and the new cursor position (after the record's trailing
/// byte).
fn read_record(
    bytes: &[u8],
    cursor: usize,
    record_index: usize,
) -> Result<(FixtureRecord, usize), LoaderError> {
    // Input-length prefix.
    let (in_len_u32, after_in_len) =
        read_u32_be_at(bytes, cursor).ok_or(LoaderError::TruncatedRecord {
            record_index,
            field: "input_length_prefix",
        })?;
    let in_len = usize::try_from(in_len_u32).map_err(|_| LoaderError::RecordTooLarge {
        record_index,
        field: "input",
        length: in_len_u32,
    })?;
    if in_len > MAX_RECORD_BYTES {
        return Err(LoaderError::RecordTooLarge {
            record_index,
            field: "input",
            length: in_len_u32,
        });
    }
    let after_in = after_in_len
        .checked_add(in_len)
        .ok_or(LoaderError::OffsetOverflow { record_index })?;
    if after_in > bytes.len() {
        return Err(LoaderError::TruncatedRecord {
            record_index,
            field: "input_payload",
        });
    }
    let input = bytes[after_in_len..after_in].to_vec();

    // Expected-length prefix.
    let (exp_len_u32, after_exp_len) =
        read_u32_be_at(bytes, after_in).ok_or(LoaderError::TruncatedRecord {
            record_index,
            field: "expected_length_prefix",
        })?;
    let exp_len = usize::try_from(exp_len_u32).map_err(|_| LoaderError::RecordTooLarge {
        record_index,
        field: "expected",
        length: exp_len_u32,
    })?;
    if exp_len > MAX_RECORD_BYTES {
        return Err(LoaderError::RecordTooLarge {
            record_index,
            field: "expected",
            length: exp_len_u32,
        });
    }
    let after_exp = after_exp_len
        .checked_add(exp_len)
        .ok_or(LoaderError::OffsetOverflow { record_index })?;
    if after_exp > bytes.len() {
        return Err(LoaderError::TruncatedRecord {
            record_index,
            field: "expected_payload",
        });
    }
    let expected = bytes[after_exp_len..after_exp].to_vec();

    Ok((FixtureRecord { input, expected }, after_exp))
}

/// Errors surfaced by the fixture loader.
///
/// Every variant carries enough information to diagnose the
/// failure from CI logs without re-running with extra
/// instrumentation.
#[derive(Debug, thiserror::Error)]
pub enum LoaderError {
    /// The underlying I/O operation failed.
    #[error("I/O error reading or writing {path:?}: {source}")]
    Io {
        /// Path the operation was issued against.
        path: PathBuf,
        /// Underlying I/O error.
        #[source]
        source: std::io::Error,
    },
    /// The byte buffer is too short to contain the 16-byte header.
    #[error("file truncated: header requires 16 bytes, found {actual}")]
    TruncatedHeader {
        /// Number of bytes actually present.
        actual: usize,
    },
    /// The file's magic bytes do not match the expected `"CXSF"`.
    #[error("bad magic bytes: expected {:?}, got {:?}", MAGIC, seen)]
    BadMagic {
        /// The four magic bytes actually read from the file.
        seen: [u8; 4],
    },
    /// The format version is not one this loader knows how to
    /// parse.
    #[error("unsupported format version {version}; loader supports v{FORMAT_VERSION}")]
    UnsupportedVersion {
        /// Version field read from the file.
        version: u32,
    },
    /// The record count exceeds platform `usize` range.
    #[error("record count {count} exceeds usize range")]
    RecordCountTooLarge {
        /// Reported record count.
        count: u32,
    },
    /// A record's declared length exceeds [`MAX_RECORD_BYTES`].
    #[error("record {record_index} field `{field}` length {length} exceeds MAX_RECORD_BYTES")]
    RecordTooLarge {
        /// Zero-based index of the offending record.
        record_index: usize,
        /// Field within the record that overflowed.
        field: &'static str,
        /// Declared length, as read from the file.
        length: u32,
    },
    /// A record's declared length exceeds the file's remaining
    /// bytes.
    #[error("record {record_index} truncated at field `{field}`")]
    TruncatedRecord {
        /// Zero-based index of the offending record.
        record_index: usize,
        /// Field within the record that ran out of bytes.
        field: &'static str,
    },
    /// Arithmetic overflow while computing a record offset.
    /// Shouldn't trigger in practice but caught to prevent panics
    /// on malformed input.
    #[error("offset arithmetic overflow at record {record_index}")]
    OffsetOverflow {
        /// Zero-based index of the offending record.
        record_index: usize,
    },
    /// The file contains trailing bytes after the last declared
    /// record.
    #[error("trailing bytes after last record: {trailing} bytes")]
    TrailingBytes {
        /// Number of trailing bytes.
        trailing: usize,
    },
}

#[cfg(test)]
mod tests {
    use super::{
        FixtureFile, FixtureKind, FixtureRecord, LoaderError, FORMAT_VERSION, MAGIC,
        MAX_RECORD_BYTES,
    };

    fn sample_records() -> Vec<FixtureRecord> {
        vec![
            FixtureRecord::new(b"hello".to_vec(), vec![0x01; 32]),
            FixtureRecord::new(b"world".to_vec(), vec![0xff; 32]),
            FixtureRecord::new(Vec::new(), Vec::new()),
        ]
    }

    /// Round-trip: build a fixture, encode, decode, equal.
    #[test]
    fn roundtrip_preserves_records() {
        let original = FixtureFile::from_records(FixtureKind::Hash, sample_records());
        let bytes = original.to_bytes();
        let decoded = FixtureFile::from_bytes(&bytes).expect("decode succeeds");
        assert_eq!(decoded, original);
    }

    /// Round-trip via the filesystem.
    #[test]
    fn roundtrip_via_disk() {
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("sample.cxsf");
        let original = FixtureFile::from_records(FixtureKind::Ecdsa, sample_records());
        original.write_to(&path).expect("write");
        let decoded = FixtureFile::load(&path).expect("load");
        assert_eq!(decoded, original);
    }

    /// Empty fixture (zero records) round-trips.
    #[test]
    fn empty_fixture_roundtrips() {
        let original = FixtureFile::new(FixtureKind::SignedAction);
        let bytes = original.to_bytes();
        let decoded = FixtureFile::from_bytes(&bytes).expect("decode");
        assert_eq!(decoded.records().len(), 0);
        assert_eq!(decoded.kind(), FixtureKind::SignedAction);
    }

    /// Custom-kind fixture round-trips with the original tag.
    #[test]
    fn custom_kind_roundtrips() {
        let original = FixtureFile::from_records(
            FixtureKind::Custom(0xDEAD_BEEF),
            vec![FixtureRecord::new(vec![1, 2, 3], vec![4, 5, 6])],
        );
        let bytes = original.to_bytes();
        let decoded = FixtureFile::from_bytes(&bytes).expect("decode");
        assert_eq!(decoded.kind(), FixtureKind::Custom(0xDEAD_BEEF));
    }

    /// Format-version field round-trips deterministically.
    #[test]
    fn format_version_is_in_header() {
        let bytes = FixtureFile::new(FixtureKind::Hash).to_bytes();
        // bytes[4..8] is the version field.
        let version_field = [bytes[4], bytes[5], bytes[6], bytes[7]];
        assert_eq!(u32::from_be_bytes(version_field), FORMAT_VERSION);
    }

    /// Truncated header → typed error.
    #[test]
    fn rejects_truncated_header() {
        let too_short = vec![0u8; 8];
        match FixtureFile::from_bytes(&too_short) {
            Err(LoaderError::TruncatedHeader { actual }) => assert_eq!(actual, 8),
            other => panic!("expected TruncatedHeader, got {other:?}"),
        }
    }

    /// Bad magic → typed error.
    #[test]
    fn rejects_bad_magic() {
        let mut bytes = FixtureFile::new(FixtureKind::Hash).to_bytes();
        bytes[0] = b'X'; // Corrupt magic.
        match FixtureFile::from_bytes(&bytes) {
            Err(LoaderError::BadMagic { seen }) => {
                assert_eq!(seen[0], b'X');
            }
            other => panic!("expected BadMagic, got {other:?}"),
        }
    }

    /// Unsupported version → typed error.
    #[test]
    fn rejects_unsupported_version() {
        let mut bytes = FixtureFile::new(FixtureKind::Hash).to_bytes();
        // Overwrite the version field with 0xFFFFFFFF.
        bytes[4..8].copy_from_slice(&u32::MAX.to_be_bytes());
        match FixtureFile::from_bytes(&bytes) {
            Err(LoaderError::UnsupportedVersion { version }) => {
                assert_eq!(version, u32::MAX);
            }
            other => panic!("expected UnsupportedVersion, got {other:?}"),
        }
    }

    /// Truncated record at the `input_payload` field → typed error
    /// with the field name.
    #[test]
    fn rejects_truncated_input_payload() {
        let mut bytes = Vec::new();
        bytes.extend_from_slice(MAGIC);
        bytes.extend_from_slice(&FORMAT_VERSION.to_be_bytes());
        bytes.extend_from_slice(&FixtureKind::Hash.to_tag().to_be_bytes());
        bytes.extend_from_slice(&1u32.to_be_bytes()); // 1 record
        bytes.extend_from_slice(&1024u32.to_be_bytes()); // claims 1024-byte input
                                                         // ... but we don't actually include 1024 bytes.
        match FixtureFile::from_bytes(&bytes) {
            Err(LoaderError::TruncatedRecord {
                record_index,
                field,
            }) => {
                assert_eq!(record_index, 0);
                assert_eq!(field, "input_payload");
            }
            other => panic!("expected TruncatedRecord(input_payload), got {other:?}"),
        }
    }

    /// Truncated record at the `input_length_prefix` field — the
    /// 4-byte length prefix runs past EOF.
    #[test]
    fn rejects_truncated_input_length_prefix() {
        // Header claims 1 record but provides only 2 bytes of the
        // record's 4-byte length-prefix field.
        let mut bytes = Vec::new();
        bytes.extend_from_slice(MAGIC);
        bytes.extend_from_slice(&FORMAT_VERSION.to_be_bytes());
        bytes.extend_from_slice(&FixtureKind::Hash.to_tag().to_be_bytes());
        bytes.extend_from_slice(&1u32.to_be_bytes());
        bytes.extend_from_slice(&[0x00, 0x00]); // 2 of 4 needed bytes
        match FixtureFile::from_bytes(&bytes) {
            Err(LoaderError::TruncatedRecord {
                record_index,
                field,
            }) => {
                assert_eq!(record_index, 0);
                assert_eq!(field, "input_length_prefix");
            }
            other => panic!("expected TruncatedRecord(input_length_prefix), got {other:?}"),
        }
    }

    /// Truncated record at the `expected_length_prefix` field — the
    /// input payload completes but the expected-length prefix runs
    /// past EOF.
    #[test]
    fn rejects_truncated_expected_length_prefix() {
        let mut bytes = Vec::new();
        bytes.extend_from_slice(MAGIC);
        bytes.extend_from_slice(&FORMAT_VERSION.to_be_bytes());
        bytes.extend_from_slice(&FixtureKind::Hash.to_tag().to_be_bytes());
        bytes.extend_from_slice(&1u32.to_be_bytes());
        bytes.extend_from_slice(&3u32.to_be_bytes()); // input length = 3
        bytes.extend_from_slice(&[0x01, 0x02, 0x03]); // input payload
                                                      // Now we should have 4 bytes for expected length, but file ends.
        match FixtureFile::from_bytes(&bytes) {
            Err(LoaderError::TruncatedRecord {
                record_index,
                field,
            }) => {
                assert_eq!(record_index, 0);
                assert_eq!(field, "expected_length_prefix");
            }
            other => panic!("expected TruncatedRecord(expected_length_prefix), got {other:?}"),
        }
    }

    /// Truncated record at the `expected_payload` field — the
    /// expected-length prefix says N bytes but only fewer remain.
    #[test]
    fn rejects_truncated_expected_payload() {
        let mut bytes = Vec::new();
        bytes.extend_from_slice(MAGIC);
        bytes.extend_from_slice(&FORMAT_VERSION.to_be_bytes());
        bytes.extend_from_slice(&FixtureKind::Hash.to_tag().to_be_bytes());
        bytes.extend_from_slice(&1u32.to_be_bytes());
        bytes.extend_from_slice(&0u32.to_be_bytes()); // empty input
        bytes.extend_from_slice(&10u32.to_be_bytes()); // claims 10 expected bytes
        bytes.extend_from_slice(&[0x01, 0x02]); // only 2 actually present
        match FixtureFile::from_bytes(&bytes) {
            Err(LoaderError::TruncatedRecord {
                record_index,
                field,
            }) => {
                assert_eq!(record_index, 0);
                assert_eq!(field, "expected_payload");
            }
            other => panic!("expected TruncatedRecord(expected_payload), got {other:?}"),
        }
    }

    /// Record-length-too-large at the `input` field → typed error.
    #[test]
    fn rejects_oversize_input_record() {
        let oversize: u32 =
            u32::try_from(MAX_RECORD_BYTES + 1).expect("MAX_RECORD_BYTES + 1 fits u32");
        let mut bytes = Vec::new();
        bytes.extend_from_slice(MAGIC);
        bytes.extend_from_slice(&FORMAT_VERSION.to_be_bytes());
        bytes.extend_from_slice(&FixtureKind::Hash.to_tag().to_be_bytes());
        bytes.extend_from_slice(&1u32.to_be_bytes()); // 1 record
        bytes.extend_from_slice(&oversize.to_be_bytes());
        match FixtureFile::from_bytes(&bytes) {
            Err(LoaderError::RecordTooLarge {
                record_index,
                field,
                length,
            }) => {
                assert_eq!(record_index, 0);
                assert_eq!(field, "input");
                assert_eq!(length, oversize);
            }
            other => panic!("expected RecordTooLarge(input), got {other:?}"),
        }
    }

    /// Record-length-too-large at the `expected` field → typed
    /// error.  The [`MAX_RECORD_BYTES`] bound is enforced
    /// symmetrically.
    #[test]
    fn rejects_oversize_expected_record() {
        let oversize: u32 =
            u32::try_from(MAX_RECORD_BYTES + 1).expect("MAX_RECORD_BYTES + 1 fits u32");
        let mut bytes = Vec::new();
        bytes.extend_from_slice(MAGIC);
        bytes.extend_from_slice(&FORMAT_VERSION.to_be_bytes());
        bytes.extend_from_slice(&FixtureKind::Hash.to_tag().to_be_bytes());
        bytes.extend_from_slice(&1u32.to_be_bytes()); // 1 record
        bytes.extend_from_slice(&0u32.to_be_bytes()); // empty input
        bytes.extend_from_slice(&oversize.to_be_bytes());
        match FixtureFile::from_bytes(&bytes) {
            Err(LoaderError::RecordTooLarge {
                record_index,
                field,
                length,
            }) => {
                assert_eq!(record_index, 0);
                assert_eq!(field, "expected");
                assert_eq!(length, oversize);
            }
            other => panic!("expected RecordTooLarge(expected), got {other:?}"),
        }
    }

    /// Trailing bytes after the last record → typed error.
    #[test]
    fn rejects_trailing_bytes() {
        let mut bytes = FixtureFile::new(FixtureKind::Hash).to_bytes();
        bytes.extend_from_slice(&[0xAA, 0xBB]);
        match FixtureFile::from_bytes(&bytes) {
            Err(LoaderError::TrailingBytes { trailing }) => assert_eq!(trailing, 2),
            other => panic!("expected TrailingBytes, got {other:?}"),
        }
    }

    /// `FixtureKind::from_tag` and `to_tag` round-trip for every
    /// named variant.
    #[test]
    fn kind_tag_roundtrips() {
        for kind in [
            FixtureKind::Hash,
            FixtureKind::Ecdsa,
            FixtureKind::SignedAction,
            FixtureKind::L1Ingest,
            FixtureKind::FaultProofObserver,
            FixtureKind::L1IngestFeeSplit,
            FixtureKind::L1IngestBold,
            FixtureKind::Custom(0xABCD),
            FixtureKind::Custom(0),
        ] {
            assert_eq!(FixtureKind::from_tag(kind.to_tag()), kind);
        }
    }

    /// `FixtureKind::L1IngestFeeSplit` has the on-disk tag 6 and
    /// is pairwise-distinct from every other named variant.  Pins
    /// the new kind's wire-format identity.
    #[test]
    fn l1_ingest_fee_split_tag_is_six_and_distinct() {
        assert_eq!(FixtureKind::L1IngestFeeSplit.to_tag(), 6);
        let named = [
            FixtureKind::Hash,
            FixtureKind::Ecdsa,
            FixtureKind::SignedAction,
            FixtureKind::L1Ingest,
            FixtureKind::FaultProofObserver,
            FixtureKind::L1IngestFeeSplit,
            FixtureKind::L1IngestBold,
        ];
        for i in 0..named.len() {
            for j in (i + 1)..named.len() {
                assert_ne!(named[i].to_tag(), named[j].to_tag());
            }
        }
    }

    /// `FixtureKind::L1IngestBold` has the on-disk tag 7 and is
    /// pairwise-distinct from every other named variant.  Pins the
    /// GP.6.5 BOLD-leg corpus kind's wire-format identity.
    #[test]
    fn l1_ingest_bold_tag_is_seven_and_distinct() {
        assert_eq!(FixtureKind::L1IngestBold.to_tag(), 7);
        assert_eq!(FixtureKind::from_tag(7), FixtureKind::L1IngestBold);
        let named = [
            FixtureKind::Hash,
            FixtureKind::Ecdsa,
            FixtureKind::SignedAction,
            FixtureKind::L1Ingest,
            FixtureKind::FaultProofObserver,
            FixtureKind::L1IngestFeeSplit,
            FixtureKind::L1IngestBold,
        ];
        for i in 0..named.len() {
            for j in (i + 1)..named.len() {
                assert_ne!(
                    named[i].to_tag(),
                    named[j].to_tag(),
                    "named kinds {:?} and {:?} share a tag",
                    named[i],
                    named[j]
                );
            }
        }
    }

    /// `push` appends records in order.
    #[test]
    fn push_appends_in_order() {
        let mut fixture = FixtureFile::new(FixtureKind::Hash);
        fixture.push(FixtureRecord::new(vec![1], vec![2]));
        fixture.push(FixtureRecord::new(vec![3], vec![4]));
        assert_eq!(fixture.records().len(), 2);
        assert_eq!(fixture.records()[0].input, vec![1]);
        assert_eq!(fixture.records()[1].input, vec![3]);
    }

    /// `from_bytes` of a file with one zero-length input + zero-
    /// length expected succeeds and yields a zero-byte record.
    #[test]
    fn zero_length_record_roundtrips() {
        let original = FixtureFile::from_records(
            FixtureKind::Hash,
            vec![FixtureRecord::new(Vec::new(), Vec::new())],
        );
        let bytes = original.to_bytes();
        let decoded = FixtureFile::from_bytes(&bytes).expect("decode");
        assert_eq!(decoded, original);
    }

    /// I/O error path: load from a non-existent file.
    #[test]
    fn load_missing_file_returns_io_error() {
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("does-not-exist.cxsf");
        match FixtureFile::load(&path) {
            Err(LoaderError::Io { path: p, .. }) => assert_eq!(p, path),
            other => panic!("expected Io error, got {other:?}"),
        }
    }

    /// Encoding is deterministic: two `to_bytes` calls on the same
    /// fixture produce byte-identical output.  This is the property
    /// fixture-regeneration in CI hinges on: a Lean-side generator
    /// that emits the same vectors must emit byte-identical files.
    #[test]
    fn encoding_is_deterministic() {
        let original = FixtureFile::from_records(FixtureKind::Hash, sample_records());
        let first = original.to_bytes();
        let second = original.to_bytes();
        assert_eq!(first, second);
    }

    /// Truncation of any single byte after a valid encoding always
    /// causes a typed error rather than a panic.  This is a
    /// fuzz-style robustness check: the loader is exposed to
    /// untrusted fixture files in CI corpora, and a panic on
    /// malformed input would manifest as opaque CI noise.
    #[test]
    fn any_truncation_returns_typed_error() {
        let original = FixtureFile::from_records(FixtureKind::Hash, sample_records());
        let full_bytes = original.to_bytes();
        // Sweep every truncation point from 0 to len-1 (i.e. every
        // single-byte truncation).  Each must yield Err, never panic.
        for cut in 0..full_bytes.len() {
            let result = FixtureFile::from_bytes(&full_bytes[..cut]);
            assert!(
                result.is_err(),
                "truncated buffer of length {cut} unexpectedly accepted"
            );
        }
    }

    /// Single-bit flips in the header / record-length fields produce
    /// typed errors rather than panics.  Defends against the
    /// length-confusion class of parser bugs.
    #[test]
    fn single_bit_flips_in_lengths_are_safe() {
        let original = FixtureFile::from_records(FixtureKind::Hash, sample_records());
        let bytes = original.to_bytes();
        // Flip each bit in the first 32 bytes (header + first
        // record-length prefix region) and check no panic results.
        for byte_idx in 0..bytes.len().min(32) {
            for bit_idx in 0..8u32 {
                let mut mutated = bytes.clone();
                mutated[byte_idx] ^= 1 << bit_idx;
                // Result is irrelevant; we're checking we don't
                // panic during decoding.
                let _ = FixtureFile::from_bytes(&mutated);
            }
        }
    }

    /// Multi-record fixture with varied-size records round-trips
    /// byte-for-byte.
    #[test]
    fn varied_size_records_roundtrip() {
        let records = vec![
            FixtureRecord::new(vec![], vec![0; 0]),
            FixtureRecord::new(vec![1], vec![2; 1]),
            FixtureRecord::new(vec![1, 2], vec![3, 4]),
            FixtureRecord::new(vec![0xff; 256], vec![0; 32]),
            FixtureRecord::new(vec![0xab; 1024], vec![0xcd; 64]),
            FixtureRecord::new(vec![], vec![0xee; 32]),
        ];
        let original = FixtureFile::from_records(FixtureKind::Hash, records);
        let decoded = FixtureFile::from_bytes(&original.to_bytes()).expect("decode");
        assert_eq!(decoded, original);
    }

    /// Records preserve byte-identity (not just structural-eq):
    /// every byte position in the input/expected fields survives
    /// round-trip exactly.
    #[test]
    fn record_bytes_are_byte_identical() {
        let mut input = Vec::with_capacity(257);
        for i in 0..=256u32 {
            // Generates 257 bytes covering every u8 value plus a
            // wraparound so byte-position 0 differs from byte-position
            // 256.
            input.push(u8::try_from(i & 0xff).expect("masked u8"));
        }
        let mut expected = Vec::with_capacity(257);
        for i in 0..=256u32 {
            expected.push(u8::try_from((i ^ 0xab) & 0xff).expect("masked u8"));
        }
        let original = FixtureFile::from_records(
            FixtureKind::Hash,
            vec![FixtureRecord::new(input.clone(), expected.clone())],
        );
        let decoded = FixtureFile::from_bytes(&original.to_bytes()).expect("decode");
        let record = &decoded.records()[0];
        assert_eq!(record.input, input);
        assert_eq!(record.expected, expected);
    }

    /// The published constants don't drift silently.
    #[test]
    fn published_constants() {
        assert_eq!(MAGIC, b"CXSF");
        assert_eq!(FORMAT_VERSION, 1);
        assert_eq!(MAX_RECORD_BYTES, 16 * 1024 * 1024);
    }

    /// A header that claims an absurdly-large record count is
    /// rejected without OOM.  This is a defence-in-depth check
    /// against the "huge count + tiny file" attack pattern: a
    /// malformed header could theoretically request [`u32::MAX`]
    /// records, but the loop bails on the first truncated record
    /// long before any large allocation occurs.
    #[test]
    fn huge_count_rejected_without_oom() {
        let mut bytes = Vec::new();
        bytes.extend_from_slice(MAGIC);
        bytes.extend_from_slice(&FORMAT_VERSION.to_be_bytes());
        bytes.extend_from_slice(&FixtureKind::Hash.to_tag().to_be_bytes());
        bytes.extend_from_slice(&u32::MAX.to_be_bytes()); // claims 4B records
                                                          // ... but no records follow.  Decoder must error on the
                                                          // first truncated record, not crash with OOM.
        match FixtureFile::from_bytes(&bytes) {
            Err(LoaderError::TruncatedRecord {
                record_index,
                field,
            }) => {
                assert_eq!(record_index, 0);
                assert_eq!(field, "input_length_prefix");
            }
            other => panic!("expected TruncatedRecord on first record, got {other:?}"),
        }
    }

    /// Round-trip preserves record order even with permuted-looking
    /// inputs.  Defends against a hypothetical encoder bug that
    /// would write records in sorted order (instead of insertion
    /// order) — the cross-stack contract requires order
    /// preservation because Lean emits in a specific, deterministic
    /// order.
    #[test]
    fn record_order_preserved() {
        // Inputs intentionally non-sorted: [c, a, b].  If the
        // encoder accidentally sorts, the round-trip output would
        // be [a, b, c] and this assertion fails.
        let records = vec![
            FixtureRecord::new(b"c".to_vec(), vec![3]),
            FixtureRecord::new(b"a".to_vec(), vec![1]),
            FixtureRecord::new(b"b".to_vec(), vec![2]),
        ];
        let original = FixtureFile::from_records(FixtureKind::Hash, records);
        let decoded = FixtureFile::from_bytes(&original.to_bytes()).expect("decode");
        assert_eq!(decoded.records()[0].input, b"c");
        assert_eq!(decoded.records()[1].input, b"a");
        assert_eq!(decoded.records()[2].input, b"b");
    }

    /// The `LoaderError` type is `Send + Sync` so it can cross
    /// thread boundaries (e.g. when reported up from a worker
    /// pool's `JoinHandle::join` result).
    #[test]
    fn loader_error_is_send_sync() {
        fn assert_send_sync<T: Send + Sync>() {}
        assert_send_sync::<LoaderError>();
    }

    /// Magic-byte buffer is exactly 4 bytes — defends against a
    /// silently-corrupted constant that would alias against random
    /// 4-byte sequences.
    #[test]
    fn magic_is_four_bytes() {
        assert_eq!(MAGIC.len(), 4);
    }
}
