// Canon  - A Societal Kernel
// Copyright (C) 2026  Adam Hall
// This program comes with ABSOLUTELY NO WARRANTY.
// This is free software, and you are welcome to redistribute it
// under certain conditions. See: https://github.com/hatter6822/Orbcrypt/blob/main/LICENSE

//! Cross-stack consistency tests for RH-B.
//!
//! ## What these tests actually verify
//!
//! Walks the `runtime/tests/cross-stack/l1_ingest.cxsf` corpus
//! and asserts that for every record:
//!
//!   1. The fixture's `input` bytes decode to a valid
//!      `FixtureInput` (event + address-book snapshot + nonce).
//!   2. Running `translation::ingest` against the input produces
//!      the `expected` bytes byte-for-byte.
//!
//! ## Caveat: this is a Rust-side self-consistency check
//!
//! The corpus file is generated by
//! `examples/gen_ingest_fixtures.rs`, which runs the SAME Rust
//! `translation::ingest` and `encoding::encode_action` that this
//! test exercises.  Strictly speaking, this verifies:
//!
//!   * The encoder / translator are byte-deterministic.
//!   * Changes to either layer surface as fixture-test failures.
//!   * Changes to the fixture binary format surface as decode
//!     failures.
//!
//! It does **not** independently verify byte-equality with the
//! Lean reference implementation
//! (`LegalKernel.Bridge.Ingest.ingest` +
//! `LegalKernel.Encoding.Action.encode`).  That verification is
//! a future Phase-5 deliverable: when Lean's
//! runtime-extraction infrastructure can emit reference bytes
//! directly, this test's `expected` field will instead be
//! Lean-sourced and the test becomes the load-bearing Rust-
//! vs.-Lean cross-stack check.
//!
//! ## Why ship this test today
//!
//! Three reasons:
//!
//!   1. **Regression detection**: changing the encoder or
//!      translator without intending to changes the fixture
//!      bytes, which surfaces as a test failure.  A reviewer
//!      reading the diff sees both the code change AND the
//!      fixture-byte change, making intent explicit.
//!   2. **Format stability**: the `.cxsf` framing layer and the
//!      `FixtureInput` / `FixtureExpected` decoders are tested
//!      against real data.
//!   3. **Documentation by example**: the corpus is a worked
//!      catalogue of every translatable event variant.
//!
//! See `docs/planning/rust_host_runtime_plan.md` §RH-B Closeout
//! for the full cross-stack-equivalence story.

use canon_cross_stack::{FixtureFile, FixtureKind};
use canon_l1_ingest::address_book::AddressBook;
use canon_l1_ingest::encoding::encode_action;
use canon_l1_ingest::fixture::{decode_expected, decode_input, FixtureExpected};
use canon_l1_ingest::translation::ingest;

/// Cross-stack contract for the `FixtureKind::L1Ingest` corpus.
#[test]
fn l1_ingest_corpus_round_trip() {
    let path = format!(
        "{}/../tests/cross-stack/l1_ingest.cxsf",
        env!("CARGO_MANIFEST_DIR")
    );
    let fixture = FixtureFile::load(&path).expect("load fixture file");
    assert!(
        matches!(fixture.kind(), FixtureKind::L1Ingest),
        "fixture kind must be L1Ingest"
    );
    assert!(
        !fixture.records().is_empty(),
        "fixture file must contain records"
    );

    for (i, record) in fixture.records().iter().enumerate() {
        // Decode the input.
        let input = decode_input(&record.input)
            .unwrap_or_else(|e| panic!("record {i}: decode input failed: {e:?}"));
        // Reconstruct the address book.
        let mut book = AddressBook::new();
        for (addr, expected_id) in &input.address_book {
            let (assigned_id, _was_new) = book.assign(addr);
            assert_eq!(
                assigned_id, *expected_id,
                "record {i}: address book replay disagreement at {addr:?}"
            );
        }
        // Run the translation.
        let actual_output = ingest(&mut book, &input.event, input.current_nonce);
        // Decode the expected output.
        let expected = decode_expected(&record.expected)
            .unwrap_or_else(|e| panic!("record {i}: decode expected failed: {e:?}"));
        // Compare.
        match (actual_output, expected) {
            (None, FixtureExpected::None) => {
                // Match: no action emitted.
            }
            (
                Some(actual),
                FixtureExpected::Some {
                    action_bytes,
                    signer,
                    nonce,
                },
            ) => {
                let actual_bytes = encode_action(&actual.action)
                    .unwrap_or_else(|e| panic!("record {i}: encode actual action failed: {e:?}"));
                assert_eq!(
                    actual_bytes, action_bytes,
                    "record {i}: action bytes differ from expected"
                );
                assert_eq!(
                    actual.signer, signer,
                    "record {i}: signer differs from expected"
                );
                assert_eq!(
                    actual.nonce, nonce,
                    "record {i}: nonce differs from expected"
                );
            }
            (None, FixtureExpected::Some { .. }) => {
                panic!("record {i}: ingest returned None but expected Some")
            }
            (Some(_), FixtureExpected::None) => {
                panic!("record {i}: ingest returned Some but expected None")
            }
        }
    }
}

/// The fixture file is non-trivial: at least 10 records covering
/// every variant the translator handles.
#[test]
fn l1_ingest_corpus_coverage() {
    let path = format!(
        "{}/../tests/cross-stack/l1_ingest.cxsf",
        env!("CARGO_MANIFEST_DIR")
    );
    let fixture = FixtureFile::load(&path).expect("load fixture file");
    assert!(
        fixture.records().len() >= 10,
        "fixture file must have at least 10 records, found {}",
        fixture.records().len()
    );
}

/// Re-encoding decoded fixture inputs round-trips.
#[test]
fn l1_ingest_corpus_input_round_trips() {
    use canon_l1_ingest::fixture::encode_input;
    let path = format!(
        "{}/../tests/cross-stack/l1_ingest.cxsf",
        env!("CARGO_MANIFEST_DIR")
    );
    let fixture = FixtureFile::load(&path).expect("load fixture file");
    for (i, record) in fixture.records().iter().enumerate() {
        let input = decode_input(&record.input)
            .unwrap_or_else(|e| panic!("record {i}: decode input failed: {e:?}"));
        let re_encoded = encode_input(&input)
            .unwrap_or_else(|e| panic!("record {i}: re-encode input failed: {e:?}"));
        assert_eq!(
            re_encoded, record.input,
            "record {i}: input does not round-trip"
        );
    }
}

/// `preview_ingest` + `commit_assignment` produce the same
/// output as `ingest` for every corpus record.  This pins the
/// equivalence between the eager-mutation API (used by the
/// fixture generator) and the peek/commit API (used by the
/// production watcher).
#[test]
fn l1_ingest_preview_and_ingest_agree() {
    use canon_l1_ingest::translation::{commit_assignment, preview_ingest, Translated};
    let path = format!(
        "{}/../tests/cross-stack/l1_ingest.cxsf",
        env!("CARGO_MANIFEST_DIR")
    );
    let fixture = FixtureFile::load(&path).expect("load fixture file");
    for (i, record) in fixture.records().iter().enumerate() {
        let input = decode_input(&record.input)
            .unwrap_or_else(|e| panic!("record {i}: decode input failed: {e:?}"));
        // Eager-mutation flow.
        let mut book_eager = AddressBook::new();
        for (addr, _) in &input.address_book {
            book_eager.assign(addr);
        }
        let eager_output = ingest(&mut book_eager, &input.event, input.current_nonce);
        // Peek/commit flow.
        let mut book_peek = AddressBook::new();
        for (addr, _) in &input.address_book {
            book_peek.assign(addr);
        }
        let peek_output = match preview_ingest(&book_peek, &input.event, input.current_nonce) {
            Translated::NoAction => None,
            Translated::Emit(u) => Some(u),
            Translated::EmitWithAssignment {
                action,
                address,
                new_actor_id,
            } => {
                commit_assignment(&mut book_peek, &address, new_actor_id).unwrap();
                Some(action)
            }
        };
        // Both flows produce the same UnsignedAction.
        assert_eq!(
            eager_output, peek_output,
            "record {i}: preview/commit flow disagrees with ingest"
        );
        // And the resulting books should match.
        for id in 1..book_eager.next_actor_id() {
            assert_eq!(
                book_eager.lookup_reverse(id),
                book_peek.lookup_reverse(id),
                "record {i}: address-book mismatch at id {id}"
            );
        }
    }
}
